# 关键情节锚点检测器配置

# 检测阈值设置
thresholds:
  emotion:
    significant_change: 0.35    # 显著情感变化阈值
    peak_value: 0.8            # 高潮情感阈值
    valley_value: -0.7         # 低谷情感阈值
    min_duration: 2.0          # 最小持续时间（秒）
  
  character:
    interaction_score: 0.65    # 角色互动重要性阈值
    relationship_change: 0.5   # 关系变化阈值
    centrality_weight: 1.5     # 中心性权重
  
  suspense:
    setup_threshold: 0.6       # 悬念设置阈值
    resolution_distance: 0.2   # 悬念解决距离（相对位置）
    open_end_score: 0.7        # 开放式结局评分

# 锚点优先级
priority_weights:
  emotion_anchors: 1.2         # 情感锚点权重
  character_anchors: 1.0       # 人物锚点权重
  suspense_anchors: 1.1        # 悬念锚点权重
  conflict_anchors: 1.3        # 冲突锚点权重
  revelation_anchors: 1.4      # 揭示锚点权重

# 检测窗口设置
detection_windows:
  sliding_window_size: 5       # 滑动窗口大小（字幕/场景数）
  overlap_ratio: 0.5           # 窗口重叠比例
  min_anchor_separation: 0.05  # 最小锚点间隔（相对位置）

# 特征提取设置
feature_extraction:
  use_dialog_features: true    # 使用对话特征
  use_visual_cues: true        # 使用视觉线索
  use_audio_features: true     # 使用音频特征
  use_narrative_context: true  # 使用叙事上下文

# 模型设置 - 预留配置，不立即加载英文模型
models:
  emotion:
    chinese:
      path: "models/emotion/chinese_emotion_model"
      threshold: 0.65
      enabled: true
    english:
      path: "models/emotion/english_emotion_model"
      threshold: 0.65
      enabled: false  # 暂不加载英文模型
  
  character:
    chinese:
      path: "models/character/chinese_character_model"
      threshold: 0.7
      enabled: true
    english:
      path: "models/character/english_character_model"
      threshold: 0.7
      enabled: false  # 暂不加载英文模型
  
  suspense:
    chinese:
      path: "models/suspense/chinese_suspense_model"
      threshold: 0.65
      enabled: true
    english:
      path: "models/suspense/english_suspense_model"
      threshold: 0.65
      enabled: false  # 暂不加载英文模型

# 锚点合并策略
merge_strategy:
  proximity_threshold: 0.05    # 临近阈值（相对位置）
  confidence_boost: 0.1        # 合并后置信度提升
  importance_method: "max"     # 重要性计算方法: max, avg, weighted_avg

# 可视化设置
visualization:
  color_map:
    emotion: "#E63946"         # 情感锚点颜色
    character: "#457B9D"       # 人物锚点颜色
    suspense: "#1D3557"        # 悬念锚点颜色
    conflict: "#F1C40F"        # 冲突锚点颜色
    revelation: "#2ECC71"      # 揭示锚点颜色
  
  timeline:
    show_confidence: true      # 显示置信度
    show_importance: true      # 显示重要性
    show_descriptions: true    # 显示描述

# 缓存设置
caching:
  enable_cache: true           # 启用缓存
  cache_dir: "cache/anchors"   # 缓存目录
  expiration_days: 7           # 缓存过期天数

# 调试设置
debug:
  verbose_output: false        # 详细输出
  save_intermediates: false    # 保存中间结果
  log_detection_details: false # 记录检测细节 