# 叙事结构选择器配置文件

# 叙事模式定义
narrative_patterns:
  # 倒叙风暴：从高潮倒叙揭示前因后果
  flashback_storm:
    steps: ["高潮前置", "回忆插叙", "悬念回收", "真相呈现"]
    suitability: ["悬疑", "推理", "犯罪", "心理"]
    description: "从故事高潮场景开始，通过回忆或倒叙方式展现前因后果"
    min_anchors: 3
    anchor_types: ["emotion", "suspense", "revelation"]
    emotion_tone: "紧张"
    pace: "medium"
    beat_distribution:
      exposition: 0.20
      flashback: 0.50
      resolution: 0.30
  
  # 多线织网：多角色多线索交织
  multi_thread:
    steps: ["线索铺设", "视角转换", "平行发展", "线索汇聚"]
    suitability: ["群像", "史诗", "都市"]
    description: "多条故事线并行发展，呈现不同角色视角，最终汇聚成完整叙事"
    min_anchors: 4
    anchor_types: ["character", "emotion", "transition"]
    emotion_tone: "复杂"
    pace: "fast"
    beat_distribution:
      setup: 0.25
      development: 0.50
      convergence: 0.25
  
  # 环形结构：首尾呼应，循环暗示
  circular_narrative:
    steps: ["开场伏笔", "中段发展", "尾部呼应", "意义升华"]
    suitability: ["文艺", "寓言", "哲理", "文学"]
    description: "故事结尾与开头呼应，形成循环结构，暗示深层主题"
    min_anchors: 3
    anchor_types: ["transition", "emotion", "resolution"]
    emotion_tone: "深沉"
    pace: "slow"
    beat_distribution:
      exposition: 0.25
      development: 0.50
      echo: 0.25
  
  # 高潮迭起：连续性情感高潮
  escalating_peaks:
    steps: ["初步铺垫", "首波高潮", "过渡平缓", "次波高潮", "最终高潮"]
    suitability: ["动作", "冒险", "战争", "竞技"]
    description: "层层递进的紧张感与冲突，呈现多个高潮点，保持节奏感"
    min_anchors: 5
    anchor_types: ["emotion", "climax", "conflict"]
    emotion_tone: "激烈"
    pace: "fast"
    beat_distribution:
      setup: 0.15
      first_peak: 0.20
      second_peak: 0.25
      final_peak: 0.40
  
  # 并行交替：两条线索平行推进
  parallel_montage:
    steps: ["双线设定", "平行推进", "交点转折", "统一结局"]
    suitability: ["爱情", "双主角", "对比", "遭遇战"]
    description: "两条叙事线并行发展，通过交替场景展现不同但相关的故事线"
    min_anchors: 4
    anchor_types: ["character", "transition", "emotion"]
    emotion_tone: "对比"
    pace: "medium"
    beat_distribution:
      setup_a: 0.15
      setup_b: 0.15
      development_a: 0.20
      development_b: 0.20
      convergence: 0.30

# 结构选择算法配置
structure_selection:
  match_threshold: 0.6     # 匹配阈值
  anchor_weight: 0.7       # 锚点匹配权重
  genre_weight: 0.8        # 类型匹配权重
  emotion_weight: 0.5      # 情感匹配权重
  pace_weight: 0.4         # 节奏匹配权重
  min_confidence: 0.5      # 最小置信度要求

# 锚点映射配置
anchor_mapping:
  position_tolerance: 0.1  # 锚点位置容差
  importance_threshold: 0.6  # 重要锚点阈值
  emotion_anchors_weight: 1.2  # 情感锚点权重
  character_anchors_weight: 1.0  # 人物锚点权重
  suspense_anchors_weight: 1.1  # 悬念锚点权重

# 模型配置 - 保留英文模型的配置但不立即加载
models:
  genre_classifier:
    chinese:
      path: "models/genre/chinese_genre_classifier"
      threshold: 0.65
      enabled: true
    english:
      path: "models/genre/english_genre_classifier"
      threshold: 0.65
      enabled: false  # 暂不加载英文模型
  
  structure_recommender:
    chinese:
      path: "models/structure/chinese_structure_recommender"
      threshold: 0.7
      enabled: true
    english:
      path: "models/structure/english_structure_recommender"
      threshold: 0.7
      enabled: false  # 暂不加载英文模型

# 可视化设置
visualization:
  color_map:
    flashback_storm: "#E63946"      # 倒叙风暴颜色
    multi_thread: "#457B9D"         # 多线织网颜色
    circular_narrative: "#1D3557"   # 环形结构颜色
    escalating_peaks: "#F1C40F"     # 高潮迭起颜色
    parallel_montage: "#2ECC71"     # 并行交替颜色
  
  structure_diagram:
    show_confidence: true           # 显示置信度
    show_anchors: true              # 显示锚点映射
    show_descriptions: true         # 显示描述

# 调试设置
debug:
  verbose_output: false             # 详细输出
  save_intermediates: false         # 保存中间结果
  log_selection_details: false      # 记录选择细节 