# 跨媒介模式迁移配置

# 支持的媒介类型
media_types:
  - 短视频
  - 互动剧
  - 广播剧
  - 漫画
  - 电影
  - 网剧
  - 动画

# 各媒介类型的适配规则
adaptation_rules:
  # 短视频适配规则
  短视频:
    duration_factor: 0.4       # 时长缩短到40%
    narrative_density: 2.0     # 叙事密度提高1倍
    pattern_priorities:        # 优先保留的模式类型
      - climax                 # 高潮
      - conflict               # 冲突
      - surprise               # 惊喜
    focus_areas:               # 重点关注区域
      - opening                # 开场
      - ending                 # 结束
    content_compression: 0.6   # 内容压缩率
    hook_emphasis: 1.5         # 钩子强调倍率
    tempo_multiplier: 1.8      # 节奏加速倍率
  
  # 互动剧适配规则
  互动剧:
    branching_factor: 2.0      # 分支因子
    decision_points:           # 决策点放置位置
      - conflict               # 冲突点
      - climax                 # 高潮点
      - resolution             # 解决点
    minimal_branches: 2        # 最少分支数
    branching_threshold: 0.7   # 分支阈值
    player_agency_level: 0.8   # 玩家能动性水平
    choice_consequence_strength: 0.75  # 选择后果强度
    narrative_flexibility: 0.6  # 叙事灵活性
  
  # 广播剧适配规则
  广播剧:
    audio_hints: true          # 使用声音提示
    voice_emphasis: 1.5        # 语音强调因子
    background_audio: true     # 使用背景音效
    narrative_pacing: 1.2      # 叙事节奏因子
    sound_effect_density: 0.8  # 音效密度
    voice_modulation_range: 0.6  # 语音调制范围
    silence_utilization: 0.5   # 静默利用率
    ambient_sound_layers: 2    # 环境音层数
  
  # 漫画适配规则
  漫画:
    visual_emphasis: true      # 视觉强调
    panel_transitions:         # 面板过渡类型
      - moment                 # 瞬间到瞬间
      - action                 # 动作到动作
      - subject                # 主体到主体
      - scene                  # 场景到场景
      - aspect                 # 角度到角度
    keyword_highlighting: true # 关键词突出显示
    scene_compression: 1.8     # 场景压缩因子
    panel_count_multiplier: 1.2  # 面板数量乘数
    visual_symbol_density: 0.7   # 视觉符号密度
    gutters_as_pacing: true      # 使用间隙作为节奏
  
  # 电影适配规则
  电影:
    cinematic_techniques:      # 电影技巧
      - establishing_shot      # 建立镜头
      - closeup                # 特写
      - pan                    # 平移
      - tracking               # 跟踪
      - drone                  # 无人机镜头
    scene_duration_factor: 1.0 # 场景时长因子
    visual_storytelling: true  # 视觉叙事
    audio_visual_sync: true    # 音视频同步
    shot_variety_level: 0.8    # 镜头多样性水平
    scene_transition_style: "dissolve"  # 场景转换风格
    camera_movement_frequency: 0.6      # 相机移动频率
  
  # 网剧适配规则
  网剧:
    episode_hooks: true        # 使用集末钩子
    character_focus: true      # 角色聚焦
    cliffhanger_frequency: 0.8 # 悬念频率
    recurring_elements: true   # 使用重复元素
    episode_length_minutes: 40 # 单集长度（分钟）
    season_arc_structure: true # 季弧结构
    subplot_density: 0.7       # 副线密度
    character_development_pace: 0.5     # 角色发展节奏
  
  # 动画适配规则
  动画:
    visual_exaggeration: 1.5   # 视觉夸张因子
    stylization_level: 0.7     # 风格化程度
    movement_emphasis: true    # 动作强调
    color_psychology: true     # 色彩心理学
    animation_style: "2D"      # 动画风格
    expression_amplification: 1.3       # 表情放大
    physics_flexibility: 0.8   # 物理法则灵活性
    visual_metaphor_usage: 0.6 # 视觉隐喻使用率

# 模式类型的适配方法
pattern_adaptation:
  # 开场模式适配方法
  opening:
    short_video: "compress"            # 压缩
    interactive: "branch_setup"        # 设置分支
    radio_drama: "audio_intro"         # 音频介绍
    comic: "visual_hook"               # 视觉钩子
    movie: "establishing"              # 建立场景
    web_series: "character_intro"      # 角色介绍
    animation: "stylized_intro"        # 风格化介绍
  
  # 高潮模式适配方法
  climax:
    short_video: "intensify"           # 强化
    interactive: "decision_point"      # 决策点
    radio_drama: "audio_peak"          # 音频高潮
    comic: "dramatic_panel"            # 戏剧性面板
    movie: "visual_climax"             # 视觉高潮
    web_series: "episode_peak"         # 剧集高潮
    animation: "dynamic_movement"      # 动态运动
  
  # 冲突模式适配方法
  conflict:
    short_video: "compress"            # 压缩
    interactive: "choice_moment"       # 选择时刻
    radio_drama: "dialogue_tension"    # 对话紧张
    comic: "contrast_panels"           # 对比面板
    movie: "conflict_sequence"         # 冲突序列
    web_series: "character_clash"      # 角色冲突
    animation: "exaggerated_conflict"  # 夸张冲突
  
  # 过渡模式适配方法
  transition:
    short_video: "minimal"             # 最小化
    interactive: "path_connection"     # 路径连接
    radio_drama: "audio_bridge"        # 音频桥接
    comic: "panel_transition"          # 面板过渡
    movie: "visual_transition"         # 视觉过渡
    web_series: "scene_shift"          # 场景转换
    animation: "fluid_transition"      # 流畅过渡
  
  # 解决模式适配方法
  resolution:
    short_video: "simplify"            # 简化
    interactive: "outcome_reveal"      # 结果揭示
    radio_drama: "tone_resolution"     # 语调解决
    comic: "visual_conclusion"         # 视觉结论
    movie: "emotional_payoff"          # 情感回报
    web_series: "arc_completion"       # 弧线完成
    animation: "visual_harmony"        # 视觉和谐
  
  # 结束模式适配方法
  ending:
    short_video: "strong_hook"         # 强钩子
    interactive: "final_choice"        # 最终选择
    radio_drama: "auditory_closure"    # 听觉封闭
    comic: "final_panel"               # 最终面板
    movie: "emotional_closure"         # 情感闭合
    web_series: "next_episode_hook"    # 下一集钩子
    animation: "symbolic_ending"       # 象征性结束

# 媒介特定的调整参数
media_specific_adjustments:
  # 短视频调整参数
  short_video:
    max_duration_seconds: 60           # 最大时长（秒）
    key_pattern_count: 3               # 关键模式数量
    hook_timing_seconds: 3             # 钩子时间点（秒）
    attention_retention_optimized: true  # 注意力保持优化
  
  # 互动剧调整参数
  interactive:
    avg_playthrough_minutes: 25        # 平均游戏时长（分钟）
    choice_points_per_scene: 1.5       # 每场景选择点数量
    narrative_convergence_points: 3    # 叙事汇聚点数量
    replay_value_optimized: true       # 重玩价值优化
  
  # 其他媒介类型的调整参数...

# 适配质量检查参数
quality_checks:
  minimal_adaptation_score: 0.7        # 最低适配分数
  structure_preservation_threshold: 0.6  # 结构保留阈值
  media_specific_features_minimum: 3   # 媒介特定特征最小数量
  validation_required: true            # 是否需要验证 