version: "1.0.0"
description: "压缩模块硬件加速配置"

# 全局硬件加速设置
hardware_acceleration:
  enabled: true                # 是否启用硬件加速
  auto_select: true            # 自动选择最佳硬件
  fallback_to_cpu: true        # 硬件不可用时回退到CPU
  benchmark_on_startup: false  # 启动时执行基准测试
  stats_tracking: true         # 跟踪性能统计
  
# CUDA/GPU 配置
cuda:
  enabled: true                # 是否启用CUDA加速
  preferred_device: 0          # 首选CUDA设备ID
  min_data_size: 1048576       # 最小数据大小(字节)，小于此值不使用GPU
  max_memory_usage: 0.7        # 最大GPU内存使用比例(0.0-1.0)
  batch_size: 8                # 批处理大小
  stream_processing: true      # 启用流处理
  algorithms:                  # 支持的算法配置
    zstd:
      enabled: true
      compression_level: 3
      threads: 1               # GPU上下文中的线程数
    lz4:
      enabled: true
      compression_level: 1
      
# Intel QAT 配置
intel_qat:
  enabled: true                # 是否启用Intel QAT加速
  device_id: 0                 # QAT设备ID
  polling_mode: false          # 启用轮询模式
  algorithms:                  # 支持的算法配置
    zstd:
      enabled: true
      compression_level: 3
      
# CPU 回退配置
cpu_fallback:
  compression_level: 3         # CPU压缩级别
  threads: 0                   # 自动(0)或指定线程数
  prioritize_process: false    # 是否优先处理而非压缩质量
  
# 资源类型特定配置
resource_specific:
  metadata:                    # 元数据
    hardware: "cpu"            # 始终使用CPU
    algorithm: "zstd"
    level: 9                   # 高压缩比
    
  model_weights:               # 模型权重
    hardware: "auto"           # 自动选择
    algorithm: "zstd"
    level: 3
    
  images:                      # 图像数据
    hardware: "cuda"           # 优先使用GPU
    algorithm: "lz4"
    level: 1                   # 快速压缩
    min_size: 65536            # 最小大小(字节)
    
  audio:                       # 音频数据
    hardware: "cuda"
    algorithm: "zstd"
    level: 3
    
  text_data:                   # 文本数据
    hardware: "cpu"            # CPU往往更适合小文本
    algorithm: "zstd"
    level: 5
    
  subtitles:                   # 字幕数据
    hardware: "cpu"
    algorithm: "zstd"
    level: 9
  
# 设备类型特定配置
device_specific:
  low_end:                     # 低端设备
    cuda:
      enabled: false           # 禁用CUDA
    cpu_fallback:
      compression_level: 3
      threads: 1
      
  mid_range:                   # 中端设备
    cuda:
      enabled: true
      max_memory_usage: 0.5    # 限制GPU内存使用
    cpu_fallback:
      compression_level: 5
      threads: 2
      
  high_end:                    # 高端设备
    cuda:
      enabled: true
      max_memory_usage: 0.8    # 允许更多GPU内存使用
    cpu_fallback:
      compression_level: 7
      threads: 4
      
# 性能平衡配置
performance_profiles:
  battery_saving:              # 省电模式
    cuda:
      enabled: false           # 禁用GPU以省电
    cpu_fallback:
      compression_level: 3
      threads: 1
      
  balanced:                    # 平衡模式
    cuda:
      enabled: true
      max_memory_usage: 0.5
    cpu_fallback:
      compression_level: 5
      threads: 0               # 自动
      
  maximum_performance:         # 最高性能模式
    cuda:
      enabled: true
      max_memory_usage: 0.9
    cpu_fallback:
      compression_level: 3     # 较低压缩比以提高速度
      threads: 0               # 自动
      
# 内存压力相关配置
memory_pressure:
  high_pressure:               # 高内存压力
    cuda:
      enabled: true            # 继续使用GPU以减轻CPU负担
      max_memory_usage: 0.9    # 允许更多GPU内存使用
    cpu_fallback:
      compression_level: 9     # 更高压缩比
      
  medium_pressure:             # 中等内存压力
    cuda:
      enabled: true
      max_memory_usage: 0.7
    cpu_fallback:
      compression_level: 7
      
  low_pressure:                # 低内存压力
    cuda:
      enabled: true
      max_memory_usage: 0.5
    cpu_fallback:
      compression_level: 5
      
# 硬件加速器首选顺序
accelerator_priority:
  - "cuda"                     # 首选CUDA/GPU
  - "intel_qat"                # 其次Intel QAT
  - "cpu"                      # 最后CPU 