# 配置架构定义
# 此文件定义了VisionAI-ClipsMaster的全局配置架构

version: "1.0"
description: "VisionAI-ClipsMaster配置架构定义"

# 根配置架构
root_schema:
  type: "object"
  required:
    - "app"
    - "user"
    - "system"
    - "version"
  properties:
    app:
      $ref: "#/schemas/app_config"
    user:
      $ref: "#/schemas/user_config" 
    system:
      $ref: "#/schemas/system_config"
    version:
      $ref: "#/schemas/version_config"
    export:
      $ref: "#/schemas/export_config"
    advanced:
      $ref: "#/schemas/advanced_config"

# 子模式定义
schemas:
  # 应用程序配置
  app_config:
    type: "object"
    required:
      - "name"
      - "default_language"
    properties:
      name:
        type: "string"
        default: "VisionAI-ClipsMaster"
      version:
        type: "string"
        pattern: "^\\d+\\.\\d+\\.\\d+$"
        default: "1.0.0"
      default_language:
        type: "string"
        enum: ["zh_CN", "en_US"]
        default: "zh_CN"
      auto_save:
        type: "boolean"
        default: true
      auto_save_interval:
        type: "integer"
        minimum: 1
        maximum: 60
        default: 5
      recent_projects:
        type: "array"
        items:
          type: "string"
        maxItems: 10
        default: []
      theme:
        type: "string"
        enum: ["light", "dark", "system"]
        default: "system"

  # 用户配置
  user_config:
    type: "object"
    properties:
      export:
        type: "object"
        properties:
          resolution:
            type: "string"
            enum: ["720p", "1080p", "4K"]
            default: "1080p"
          frame_rate:
            type: "integer"
            minimum: 24
            maximum: 60
            default: 30
          storage:
            type: "object"
            properties:
              output_path:
                type: "string"
                default: "~/ClipsMasterOutput"
              temp_path:
                type: "string"
                default: "~/ClipsMasterTemp"
              log_path:
                type: "string"
                default: "~/ClipsMasterLogs"
          codec:
            type: "string"
            enum: ["h264", "h265", "av1", "prores"]
            default: "h264"
          format:
            type: "string"
            enum: ["mp4", "mov", "avi", "mkv"]
            default: "mp4"
      interface:
        type: "object"
        properties:
          timeline_zoom:
            type: "integer"
            minimum: 1
            maximum: 10
            default: 5
          show_waveforms:
            type: "boolean"
            default: true
          show_thumbnails:
            type: "boolean"
            default: true
          shortcut_preset:
            type: "string"
            enum: ["default", "premiere", "finalcut", "custom"]
            default: "default"
          auto_sync:
            type: "boolean"
            default: true

  # 系统配置
  system_config:
    type: "object"
    properties:
      gpu:
        type: "object"
        properties:
          enabled:
            type: "boolean"
            default: true
          device:
            type: "string"
            default: "auto"
          memory_limit:
            type: "integer"
            minimum: 512
            maximum: 16384
            default: 2048
      cpu:
        type: "object"
        properties:
          threads:
            type: "integer"
            minimum: 1
            maximum: 64
            default: "auto"
      cache:
        type: "object"
        properties:
          enabled:
            type: "boolean"
            default: true
          size_limit:
            type: "integer"
            minimum: 1024
            maximum: 102400
            default: 10240
          location:
            type: "string"
            default: "system_temp"
      logging:
        type: "object"
        properties:
          level:
            type: "string"
            enum: ["debug", "info", "warning", "error"]
            default: "info"
          file_rotation:
            type: "integer"
            minimum: 1
            maximum: 90
            default: 7
          max_size:
            type: "integer"
            minimum: 1
            maximum: 1024
            default: 100
      telemetry:
        type: "object"
        properties:
          enabled:
            type: "boolean"
            default: true
          anonymous:
            type: "boolean"
            default: true

  # 版本配置
  version_config:
    type: "object"
    properties:
      compatibility:
        type: "object"
        properties:
          target_version:
            type: "string"
            pattern: "^\\d+\\.\\d+(\\.\\d+)?$"
            default: "3.0"
          check_updates:
            type: "boolean"
            default: true
          update_interval:
            type: "integer"
            minimum: 1
            maximum: 30
            default: 7
          auto_adapt:
            type: "boolean"
            default: true
          fallback_enabled:
            type: "boolean"
            default: true
      schemas:
        type: "object"
        properties:
          default_schema:
            type: "string"
            default: "jianying_v3.xsd"
          validation_level:
            type: "string"
            enum: ["strict", "normal", "loose"]
            default: "normal"
      features:
        type: "object"
        properties:
          required_nodes:
            type: "array"
            items:
              type: "string"
            default: ["project", "sequence", "video", "audio"]
          supported_features:
            type: "array"
            items:
              type: "string"
            default: ["multi_track", "effects_layer", "subtitle_track"]

  # 导出配置
  export_config:
    type: "object"
    properties:
      presets:
        type: "array"
        items:
          type: "object"
          required:
            - "name"
            - "format"
          properties:
            name:
              type: "string"
            format:
              type: "string"
              enum: ["mp4", "mov", "avi", "mkv"]
            resolution:
              type: "string"
              enum: ["720p", "1080p", "4K"]
            frame_rate:
              type: "integer"
              minimum: 24
              maximum: 60
            codec:
              type: "string"
              enum: ["h264", "h265", "av1", "prores"]
            bitrate:
              type: "integer"
              minimum: 1000
              maximum: 100000
        default: []
      watermark:
        type: "object"
        properties:
          enabled:
            type: "boolean"
            default: false
          image:
            type: "string"
            default: ""
          opacity:
            type: "number"
            minimum: 0.0
            maximum: 1.0
            default: 0.5
          position:
            type: "string"
            enum: ["top-left", "top-right", "bottom-left", "bottom-right", "center"]
            default: "bottom-right"
      batch:
        type: "object"
        properties:
          enabled:
            type: "boolean"
            default: false
          concurrent_jobs:
            type: "integer"
            minimum: 1
            maximum: 8
            default: 2

  # 高级配置
  advanced_config:
    type: "object"
    properties:
      developer_mode:
        type: "boolean"
        default: false
      experimental_features:
        type: "boolean"
        default: false
      debug_overlay:
        type: "boolean"
        default: false
      custom_plugins:
        type: "array"
        items:
          type: "string"
        default: []
      remote_processing:
        type: "object"
        properties:
          enabled:
            type: "boolean"
            default: false
          endpoint:
            type: "string"
            default: ""
          auth_token:
            type: "string"
            default: ""
      custom_scripts:
        type: "object"
        properties:
          enabled:
            type: "boolean"
            default: false
          search_paths:
            type: "array"
            items:
              type: "string"
            default: []
      language_models:
        type: "object"
        properties:
          enabled:
            type: "boolean"
            default: false
          model_path:
            type: "string"
            default: "models/language"
          zh_model: 
            type: "string"
            default: "zh_core_web_md"
          en_model:
            type: "string"
            default: "en_core_web_md"
          load_en_model:
            type: "boolean"
            default: false  # 默认不加载英文模型 