# 时空连续性检验配置文件
# 用于控制场景连续性验证的规则与阈值

# 时间约束
time_constraints:
  max_time_jump: 1800      # 最大时间跳跃(秒)，默认30分钟
  min_transition_time: 0.5 # 最小场景过渡时间(秒)
  location_change_time: 30 # 地点变化所需最小时间(秒)

# 连续性规则开关
continuity_rules:
  location_tracking: true    # 跟踪场景地点变化
  character_tracking: true   # 跟踪角色进出场
  object_tracking: true      # 跟踪关键道具
  time_of_day_tracking: true # 跟踪时间段变化
  weather_tracking: false    # 跟踪天气变化(当前未实现)
  clothing_tracking: false   # 跟踪服装变化(当前未实现)

# 需要特别关注的关键道具列表（容易出现连续性错误的物品）
key_props:
  # 中文道具
  - 手机
  - 眼镜
  - 钱包
  - 背包
  - 手表
  - 项链
  - 钥匙
  - 耳机
  - 书本
  - 文件
  - 伞
  - 笔记本
  # 英文道具  
  - phone
  - glasses
  - wallet
  - bag
  - watch
  - necklace
  - keys
  - headphones
  - book
  - document
  - umbrella
  - notebook

# 场景位置类型
location_types:
  # 中文位置
  - 室内
  - 室外
  - 家
  - 客厅
  - 卧室
  - 厨房
  - 餐厅
  - 办公室
  - 教室
  - 学校
  - 医院
  - 商店
  - 咖啡厅
  - 公园
  - 街道
  - 车内
  # 英文位置
  - indoor
  - outdoor
  - home
  - living room
  - bedroom
  - kitchen
  - restaurant
  - office
  - classroom
  - school
  - hospital
  - store
  - cafe
  - park
  - street
  - car

# 严重程度阈值
severity_levels:
  critical: 8    # 严重问题，可能导致观众明显注意到逻辑错误
  warning: 5     # 警告，可能影响观感但不会严重破坏沉浸感
  suggestion: 2  # 建议，轻微问题，可以不处理

# 特殊场景过渡列表 - 允许特定类型的场景过渡不触发警告
allowed_transitions:
  - type: "flashback"    # 闪回
    indicators: ["回忆", "想起", "曾经", "过去", "remember", "recalled", "flashback", "memory"]
  - type: "dream"        # 梦境
    indicators: ["梦", "梦到", "梦见", "dream", "dreamed", "dreamt"]
  - type: "imagination"  # 想象
    indicators: ["想象", "幻想", "如果", "假如", "imagine", "fantasy", "what if"] 