# 跨剧本模式对齐配置文件
# 用于控制原片剧本模式与爆款剧本模式的对比分析

# 对齐算法配置
alignment:
  similarity_threshold: 0.3     # 模式相似度阈值(0-1)
  intensification_factor: 1.5   # 强化因子阈值
  max_patterns: 50              # 每类最大返回模式数
  min_impact_score: 0.4         # 最小影响力分数
  
# 强化类型配置
intensification_types:
  # 时长延长: 爆款中某场景时长比原片延长的阈值系数
  duration_extension: 1.35  
  
  # 情感放大: 爆款中情感强度比原片放大的阈值系数
  emotion_amplification: 1.5
  
  # 冲突升级: 爆款中冲突强度比原片升级的阈值系数
  conflict_escalation: 2.0
  
  # 惊喜增强: 爆款中惊喜元素比原片增强的阈值系数
  surprise_enhancement: 1.8
  
  # 悬念构建: 爆款中悬念元素比原片增加的阈值系数
  suspense_building: 1.7
  
  # 转场速度: 爆款中场景转换速度比原片加快的阈值系数
  transition_speed: 1.4
  
  # 视觉冲击: 爆款中视觉冲击比原片增强的阈值系数
  visual_impact: 1.6

# 增强模式规则
enhancement_rules:
  # 高潮增强规则
  climax:
    # 高潮场景需要增强的特定方面
    aspects:
      - "emotion_intensity"      # 情感强度
      - "conflict_level"         # 冲突程度
      - "surprise_factor"        # 惊喜因素
    
    # 高潮场景的理想特征
    ideal_features:
      min_duration: 12           # 最小持续时间(秒)
      max_duration: 40           # 最大持续时间(秒)
      emotion_intensity: 0.9     # 目标情感强度(0-1)
      conflict_level: 0.8        # 目标冲突强度(0-1)
  
  # 铺垫增强规则
  exposition:
    aspects:
      - "information_density"    # 信息密度
      - "foreshadowing"          # 伏笔设置
    
    ideal_features:
      min_duration: 5            # 最小持续时间(秒)
      max_duration: 15           # 最大持续时间(秒)
      information_density: 0.6   # 目标信息密度(0-1)
      
  # 解决方案增强规则
  resolution:
    aspects:
      - "satisfaction_level"     # 满足感程度
      - "closure_quality"        # 结束质量
    
    ideal_features:
      min_duration: 8            # 最小持续时间(秒)
      max_duration: 20           # 最大持续时间(秒)
      satisfaction_level: 0.8    # 目标满足感(0-1)

# 模式匹配配置
pattern_matching:
  algorithm: "semantic"          # 匹配算法: exact(精确), fuzzy(模糊), semantic(语义)
  min_similarity: 0.5            # 最小相似度
  context_window: 2              # 上下文窗口大小(句子数)
  
  # 模式匹配权重
  weights:
    keyword_match: 0.3           # 关键词匹配权重
    structure_match: 0.4         # 结构匹配权重
    semantic_match: 0.3          # 语义匹配权重

# 输出优化配置
output:
  format: "detailed"             # 输出格式: simple, detailed, visual
  sort_by: "impact_score"        # 排序方式: impact_score, confidence, support
  group_by: "type"               # 分组方式: type, category, none
  include_stats: true            # 是否包含统计信息
  highlight_top: 3               # 高亮前N个最重要的模式 