# 情感焦点定位器配置

# 焦点检测配置
focus_detection:
  # 情感得分阈值，高于此值的句子被视为情感焦点
  emotion_score_threshold: 0.7
  
  # 各特征权重
  body_language_weight: 0.2    # 肢体动作描述权重
  dialogue_weight: 0.15        # 对话特征权重
  exclamation_weight: 0.1      # 感叹词和强调权重
  
  # 上下文配置
  context_window: 20           # 上下文窗口大小(字符数)
  merge_proximity: 10          # 合并相邻焦点的最大距离

# 肢体动作描述词
body_language_patterns:
  # 基础肢体动作
  - "摇头"
  - "点头"
  - "皱眉"
  - "微笑"
  - "大笑"
  - "哭泣"
  - "叹气"
  - "颤抖"
  - "拥抱"
  - "握手"
  # 强烈肢体动作
  - "举手"
  - "挥手"
  - "跺脚"
  - "跳起"
  - "后退"
  - "前进"
  - "转身"
  - "倒下"
  - "站起"
  - "推开"
  - "拉近"
  - "拍打"
  - "挥舞"
  - "捶打"
  - "甩动"
  - "踢"
  # 脸部表情
  - "瞪大眼睛"
  - "眯眼"
  - "咬唇"
  - "眨眼"
  - "流泪"
  - "抿嘴"
  - "眉头紧锁"
  - "嘴角上扬"
  - "嘴角下垂"
  - "俯首"
  - "仰头"

# 情感对话标记词
emotional_dialogue_markers:
  # 标点符号
  - "!"      # 感叹号
  - "?!"     # 问号+感叹号
  - "..."    # 省略号
  - "？！"    # 中文问号+感叹号
  - "。。。"  # 中文省略号
  
  # 感叹词(中文)
  - "啊"
  - "哎"
  - "哦"
  - "唉"
  - "呀"
  - "哇"
  - "呜"
  - "哎呀"
  - "天啊"
  - "我的天"
  - "天哪"
  - "哼"
  - "嘿"
  - "喂"
  
  # 强烈情感表达
  - "太"
  - "非常"
  - "极其"
  - "绝对"
  - "真是"
  - "简直"
  - "真的"
  - "太过"
  - "无比"
  - "无法"

# 强调模式
emphasis_patterns:
  # 文本强调
  - "【.+】"      # 方括号强调
  - "「.+」"      # 书名号强调
  - "『.+』"      # 书名号强调
  - "［.+］"      # 全角方括号强调
  - "(.+)"       # 小括号(一般不是强调，权重较低)
  
  # 重复模式
  - "(.+)\\1+"   # 文本重复模式
  
  # 特殊模式
  - "[A-Z]{2,}"  # 全大写字母(英文)

# 输出配置
output:
  include_context: true        # 是否在结果中包含上下文
  max_focus_points: 10         # 最多返回的焦点数
  min_focus_length: 5          # 最小焦点长度(字符数)
  max_focus_length: 200        # 最大焦点长度(字符数) 