# 导出配置文件
# 管理导出相关设置和预设

export_config_schema:
  presets:
    type: "array"
    items:
      type: "object"
      required:
        - "name"
        - "format"
      properties:
        name:
          type: "str"
        format:
          type: "str"
          enum: ["mp4", "mov", "avi", "mkv"]
        resolution:
          type: "str"
          enum: ["720p", "1080p", "4K"]
        frame_rate:
          type: "int"
          min: 24
          max: 60
        codec:
          type: "str"
          enum: ["h264", "h265", "av1", "prores"]
        bitrate:
          type: "int"
          min: 1000
          max: 100000
    default: []
  
  watermark:
    enabled:
      type: "bool"
      default: false
    image:
      type: "str"
      default: ""
    opacity:
      type: "float"
      min: 0.0
      max: 1.0
      default: 0.5
    position:
      type: "str"
      enum: ["top-left", "top-right", "bottom-left", "bottom-right", "center"]
      default: "bottom-right"
  
  batch:
    enabled:
      type: "bool"
      default: false
    concurrent_jobs:
      type: "int"
      min: 1
      max: 8
      default: 2
  
  version_specific:
    use_version_specific_settings:
      type: "bool"
      default: true
    fallback_version:
      type: "str"
      default: "3.0"

# 预定义导出预设
export_presets:
  - name: "网络视频 (1080p)"
    format: "mp4"
    resolution: "1080p"
    frame_rate: 30
    codec: "h264"
    bitrate: 8000
  
  - name: "高质量 (4K)"
    format: "mp4"
    resolution: "4K"
    frame_rate: 30
    codec: "h265"
    bitrate: 40000
  
  - name: "社交媒体 (720p)"
    format: "mp4"
    resolution: "720p"
    frame_rate: 30
    codec: "h264"
    bitrate: 4000
  
  - name: "专业编辑用 (ProRes)"
    format: "mov"
    resolution: "1080p"
    frame_rate: 30
    codec: "prores"
    bitrate: 50000

# 版本特定的输出设置
version_output_settings:
  "3.0":
    max_resolution: "4K"
    max_frame_rate: 60
    codecs: ["h264", "h265", "av1", "prores"]
  
  "2.5":
    max_resolution: "1080p"
    max_frame_rate: 60
    codecs: ["h264", "h265", "prores"]
  
  "2.0":
    max_resolution: "1080p"
    max_frame_rate: 30
    codecs: ["h264"]
  
  "1.0":
    max_resolution: "720p"
    max_frame_rate: 30
    codecs: ["h264"]

# 默认设置
default_settings:
  presets: []  # 使用预定义的预设
  watermark:
    enabled: false
    image: ""
    opacity: 0.5
    position: "bottom-right"
  batch:
    enabled: false
    concurrent_jobs: 2
  version_specific:
    use_version_specific_settings: true
    fallback_version: "3.0" 