compatibility:
  "\u526A\u6620v8.9": 0.7
  "\u526A\u6620v9.0": 0.85
  "\u526A\u6620v9.1": 0.92
  "\u526A\u6620v9.2": 0.95
default_format: jianying
formats:
  davinci:
    enabled: true
    template_path: templates/davinci_template.xml
    version: '18'
  jianying:
    enabled: true
    template_path: templates/jianying_template.jy
    version: '9.2'
  mp4:
    bitrate: 4M
    codec: h264
    enabled: true
    resolution: source
preferences:
  auto_open: true
  quality_priority: speed
  save_intermediates: false
