# 沉浸感增强模块配置

# 视觉效果配置
visual_effects:
  # 是否启用视觉效果增强
  enabled: true
  
  # 默认视觉增强方式
  default_enhancements:
    - zoom_focus
    - blur_effect
  
  # 场景类型对应的视觉效果
  scene_types:
    emotional:
      - slow_motion
      - blur_effect
      - zoom_focus
    action:
      - timelapse
      - pov_shift
      - split_screen
    suspense:
      - blur_effect
      - zoom_focus
      - dark_filter
    revelation:
      - zoom_focus
      - slow_motion
      - bright_filter
    comedy:
      - split_screen
      - zoom_focus
      - saturated_colors
    romance:
      - slow_motion
      - blur_effect
      - warm_filter
    flashback:
      - flashback_filter
      - blur_edges
      - desaturated_colors
    dream:
      - dream_sequence
      - blur_effect
      - color_shift

# 音频效果配置
audio_effects:
  # 是否启用音频效果增强
  enabled: true
  
  # 默认音频增强方式
  default_enhancements:
    - ambient_sound
    - emotional_tune
  
  # 场景类型对应的音频效果
  scene_types:
    emotional:
      - emotional_tune
      - silence
      - voice_echo
    action:
      - sound_effect
      - music_shift
      - heart_beat
    suspense:
      - suspense_sound
      - heart_beat
      - silence
    revelation:
      - music_shift
      - silence
      - voice_echo
    comedy:
      - sound_effect
      - ambient_sound
      - music_shift
    romance:
      - emotional_tune
      - ambient_sound
      - silence
    flashback:
      - voice_echo
      - ambient_sound
      - emotional_tune
    dream:
      - ambient_sound
      - voice_echo
      - music_shift

# 转场效果配置
transition_effects:
  # 是否启用转场效果
  enabled: true
  
  # 转场效果类型
  types:
    - cross_fade
    - fade_to_black
    - whip_pan
    - jump_cut
    - match_cut
    - iris_transition
    - wipe_transition
    - morph_transition
  
  # 情感过渡对应的转场效果
  emotion_transitions:
    positive_to_negative:
      - fade_to_black
      - slow_cross_fade
    negative_to_positive:
      - bright_fade
      - quick_cross_fade
    neutral_to_positive:
      - color_boost_transition
    neutral_to_negative:
      - desaturate_transition
    
# 沉浸感模板
immersion_templates:
  # 标准模板
  standard:
    visual:
      - zoom_focus
      - blur_effect
    audio:
      - ambient_sound
      - emotional_tune
    
  # 动作模板
  action:
    visual:
      - timelapse
      - pov_shift
    audio:
      - sound_effect
      - heart_beat
    
  # 情感模板
  emotional:
    visual:
      - slow_motion
      - blur_effect
    audio:
      - emotional_tune
      - silence
    
  # 悬疑模板
  suspense:
    visual:
      - zoom_focus
      - blur_effect
    audio:
      - suspense_sound
      - silence
    
  # 喜剧模板
  comedy:
    visual:
      - split_screen
      - zoom_focus
    audio:
      - sound_effect
      - ambient_sound

# 高级设置
advanced:
  # 是否自动检测场景类型
  auto_detect_scene_type: true
  
  # 是否根据情感强度调整效果强度
  adjust_by_emotion_intensity: true
  
  # 是否保持音频连续性
  maintain_audio_continuity: true
  
  # 是否跟踪角色情感变化
  track_character_emotions: true 