alerts:
  cpu:
    critical: 95
    warning: 85
  disk:
    critical: 95
    warning: 90
  gpu:
    critical: 95
    warning: 85
  memory:
    critical: 97
    warning: 90
  temperature:
    critical: 80
    warning: 70
charts:
  gauges:
    animation_speed: 500
    show_labels: true
  trend:
    auto_scale: true
    line_width: 2
    max_points: 300
    point_size: 4
    show_grid: true
    show_legend: true
collection:
  database_storage: false
  disk_metrics: true
  network_metrics: true
  process_metrics: true
  storage_path: ~/VisionAI-Metrics
  system_metrics: true
  target_process: python
dashboard:
  history_length: 300
  refresh_interval: 1000
  theme: light
  visible_widgets:
  - cpu
  - mem
  - gpu
  - temp
logging:
  auto_analyze: true
  auto_flush: true
  backup_count: 5
  file_path: logs/monitor.log
  format: csv
  include_headers: true
  level: info
  log_interval: 5000
  max_size: 10
  retention_days: 30
performance:
  auto_mode: true
  batch_processing: true
  check_interval: 5000
  cpu_threshold: 80
  hardware_acceleration: true
  low_spec_mode:
    disable_3d: true
    disable_animations: true
    disable_antialiasing: true
    reduce_update_frequency: true
    use_text_mode: true
  throttle_updates: true
prediction:
  confidence_level: 0.95
  enabled: true
  forecast_window: 60
  interval: 10000
topology:
  auto_rotate: true
  enabled: true
  rotation_speed: 1.0
  show_grid: true
  show_labels: true
  update_interval: 2000
  view_type: bar
