# 叙事分析与剧本重构配置文件
# 用于控制短剧混剪的剧情结构与节奏

# 叙事模板配置 - 不同的剧情结构模式
narrative_templates:
  # 冲突-解决模式：从困境到胜利的情感曲线
  conflict_resolution:
    weight: 1.5             # 模板权重
    min_segments: 3         # 最小片段数
    duration_ratio: 0.4     # 占总时长的比例
    structure:              # 结构比例分配
      setup: 0.25           # 铺垫
      conflict: 0.35        # 冲突
      resolution: 0.40      # 解决
      
  # 情感过山车：剧烈的情感波动创造紧张感
  emotional_rollercoaster:
    weight: 1.2
    min_segments: 4
    duration_ratio: 0.35
    structure:
      intro: 0.15
      ups_and_downs: 0.70
      conclusion: 0.15
      
  # 揭示模式：开始积极，逐步揭露冲突或问题
  revelation:
    weight: 1.3
    min_segments: 2
    duration_ratio: 0.3
    structure:
      setup: 0.30
      reveal: 0.45
      aftermath: 0.25

# 情感分析阈值
emotion_thresholds:
  significant_change: 0.4    # 情感显著变化的阈值
  climax_intensity: 0.7      # 高潮情感强度阈值
  conflict_gap: 0.5          # 冲突情感差距阈值
  min_intensity: 0.2         # 最小情感强度要求

# 片段选择配置
segment_selection:
  min_duration: 1.5          # 最小片段时长(秒)
  max_segments: 15           # 最大片段数量
  key_segment_boost: 1.2     # 关键片段重要性提升系数
  sentiment_weight: 0.8      # 情感强度权重
  coherence_weight: 0.6      # 连贯性权重
  
  # 总时长控制（避免过短/过长）
  total_duration:
    min: 20                  # 最小总时长(秒)
    max: 120                 # 最大总时长(秒)
    target: 60               # 目标总时长(秒)
    
# 节奏控制
rhythm_control:
  max_consecutive_similar: 3  # 最大连续相似情感片段数
  transition_threshold: 0.3   # 转场情感变化阈值
  pacing:
    fast: 1.0                 # 快节奏系数
    medium: 1.5               # 中等节奏系数
    slow: 2.5                 # 慢节奏系数
    
# 高级剧本结构分析配置
advanced_analysis:
  character_focus: true       # 启用角色关系分析
  theme_extraction: true      # 启用主题提取
  plot_prediction: true       # 启用剧情预测
  continuity_check: true      # 启用连贯性检查
  emotional_arc: true         # 情感弧分析
  tension_tracking: true      # 张力追踪

# 知识图谱配置
knowledge_graph:
  # 实体提取配置
  entity_extraction:
    min_character_mentions: 2      # 角色最小提及次数
    min_location_mentions: 1       # 地点最小提及次数
    max_entities_per_type: 20      # 每类实体最大数量
  
  # 关系提取配置  
  relationship_extraction:
    proximity_threshold: 50        # 关系近邻阈值(字符)
    min_relationship_weight: 0.5   # 最小关系权重
    max_relationships: 100         # 最大关系数量
    
  # 可视化配置
  visualization:
    char_color: "skyblue"          # 角色节点颜色
    location_color: "lightgreen"   # 地点节点颜色
    event_color: "salmon"          # 事件节点颜色
    unknown_color: "gray"          # 未知类型节点颜色
    node_size: 500                 # 节点大小
    edge_alpha: 0.5                # 边透明度
    
  # 场景分割配置
  scene_segmentation:
    time_threshold: 5.0            # 场景分割时间阈值(秒)
    min_scene_duration: 10.0       # 最小场景时长(秒) 
    min_scene_subtitles: 3         # 最小场景字幕数 

# 叙事单元配置

# 节拍类型
beat_types:
  - "exposition"    # 铺垫
  - "rising_action" # 升级
  - "climax"        # 高潮
  - "resolution"    # 解决

# 长短文本处理配置
text_length:
  short_text_threshold: 300   # 短文本字符阈值
  long_text_strategy: "chunk" # 长文本策略: chunk(分块), summarize(摘要)
  chunk_size: 500             # 分块大小(字符数)
  chunk_overlap: 100          # 分块重叠(字符数)

# 节拍识别阈值
thresholds:
  min_beat_length: 10         # 最小节拍长度(字符数)
  max_beat_length: 300        # 最大节拍长度(字符数)
  min_beat_count: 2           # 最少节拍数量
  max_beat_count: 20          # 最多节拍数量
  confidence_threshold: 0.5   # 置信度阈值

# 语言配置
language:
  default: "zh"               # 默认语言
  auto_detect: true           # 自动检测语言
  supported:                  # 支持的语言列表
    - "zh"
    - "en"

# 情感分析配置
sentiment_analysis:
  enabled: true               # 是否启用情感分析
  use_fallback: true          # 使用备用情感分析器
  
# 性能配置
performance:
  memory_efficient: true      # 内存高效模式
  cache_results: true         # 缓存结果
  parallel_processing: false  # 并行处理