# Security Policy Configuration

# File Access Controls
file_access:
  allowed_directories:
    - data/input
    - data/output
    - data/training
    - models
  restricted_directories:
    - configs
    - src/core
  file_permissions:
    default_mode: 0644  # rw-r--r--
    executable_mode: 0755  # rwxr-xr-x
    sensitive_mode: 0600  # rw-------
  watch_patterns:
    - "*.py"
    - "*.yaml"
    - "*.json"
  auto_backup: true
  version_control: true

# Model Security
model_security:
  model_validation:
    check_hash: true
    verify_signature: true
    validate_checksum: true
    allowed_formats:
      - .pth
      - .onnx
      - .bin
  access_control:
    max_concurrent_loads: 2
    require_authentication: true
    session_timeout: 3600  # 1 hour
    max_failed_attempts: 5
    lockout_duration: 900  # 15 minutes
  data_protection:
    encrypt_cached_data: true
    secure_memory_clear: true
    temp_file_cleanup: true
    encryption_algorithm: "AES-256-GCM"
    key_rotation_period: 7  # days

# Network Security
network_security:
  allowed_hosts:
    - "localhost"
    - "localhost"
  port_range:
    min: 8000
    max: 8999
  ssl_config:
    enabled: true
    min_tls_version: "1.2"
    verify_cert: true
  rate_limiting:
    max_requests_per_minute: 60
    max_connections_per_ip: 10

# System Resource Protection
resource_protection:
  memory_limits:
    max_process_memory: 4096  # MB
    swap_threshold: 80  # percentage
    emergency_cleanup_threshold: 95  # percentage
  cpu_limits:
    max_threads: 4
    max_cpu_percent: 90
    throttle_threshold: 85
  disk_usage:
    max_temp_storage: 1024  # MB
    cleanup_threshold: 90  # percentage
    min_free_space: 5120  # MB
  process_isolation:
    enable_sandboxing: true
    restrict_shell_access: true

# Backup and Recovery
backup:
  auto_backup:
    enabled: true
    interval: 24  # hours
    retention_period: 30  # days
    max_backups: 10
  backup_locations:
    - path: "backup/local"
      type: "local"
    - path: "backup/remote"
      type: "remote"
  critical_files:
    - "configs/*.yaml"
    - "src/core/*.py"
    - "models/*.pth"

# Logging and Monitoring
security_monitoring:
  log_level: INFO
  log_rotation:
    max_size: 100  # MB
    backup_count: 5
  audit_events:
    - file_access
    - model_loading
    - permission_changes
    - network_access
    - authentication
    - configuration_changes
  alert_thresholds:
    failed_attempts: 3
    suspicious_activity: 5
    resource_usage: 90
  notification:
    email_alerts: true
    slack_alerts: false
    alert_severity_levels:
      - critical
      - warning
      - info

# Encryption Configuration
encryption:
  algorithm: "AES-256-GCM"
  key_management:
    key_derivation: "PBKDF2"
    iterations: 100000
    salt_size: 32
  sensitive_data:
    encrypt_config: true
    encrypt_credentials: true
    encrypt_temp_files: true 