# VisionAI-ClipsMaster UI语言配置
# 指定支持的UI语言及对应的模型语言

zh_CN:
  name: "简体中文"
  native_name: "简体中文"
  icon: "cn"
  model_code: "zh"
  enabled: true
  default: true
  description: "使用中文操作界面和中文模型"

en_US:
  name: "English (US)"
  native_name: "English (US)"
  icon: "us"
  model_code: "en"
  enabled: false  # 英文模型暂不加载
  default: false
  description: "English interface with English model" 