default_settings:
  advanced:
    developer_mode: false
    experimental_features: false
    language_models:
      enabled: false
      load_en_model: false
  export:
    codec: h264
    format: mp4
    frame_rate: 30
    resolution: 1080p
    storage:
      output_path: ~/ClipsMasterOutput
  interface:
    shortcut_preset: default
    show_thumbnails: true
    show_waveforms: true
    timeline_zoom: 5
  version:
    auto_adapt: true
    fallback_enabled: true
    target_version: '3.0'
user_config_schema:
  advanced:
    developer_mode:
      default: false
      type: bool
    experimental_features:
      default: false
      type: bool
    language_models:
      enabled:
        default: false
        type: bool
      load_en_model:
        default: false
        type: bool
  export:
    codec:
      default: h264
      enum:
      - h264
      - h265
      - av1
      - prores
      type: str
    format:
      default: mp4
      enum:
      - mp4
      - mov
      - avi
      - mkv
      type: str
    frame_rate:
      default: 30
      max: 60
      min: 24
      type: int
    resolution:
      default: 1080p
      enum:
      - 1080p
      - 4K
      - 720p
      type: str
    storage:
      output_path:
        default: ~/ClipsMasterOutput
        must_exist: false
        type: path
  interface:
    shortcut_preset:
      default: default
      enum:
      - default
      - premiere
      - finalcut
      - custom
      type: str
    show_thumbnails:
      default: true
      type: bool
    show_waveforms:
      default: true
      type: bool
    timeline_zoom:
      default: 5
      max: 10
      min: 1
      type: int
  version:
    auto_adapt:
      default: true
      type: bool
    fallback_enabled:
      default: true
      type: bool
    target_version:
      default: '3.0'
      enum:
      - '1.0'
      - '2.0'
      - '2.5'
      - '3.0'
      - '3.1'
      type: str
