# 验证沙盒配置文件
# 定义用于脚本验证的各种阈值和标准

# 剧情漏洞检测配置
plot_hole_detection:
  # 角色消失检测
  character_disappearance:
    # 角色在多少场景内未出现则视为突然消失
    absence_threshold: 3
    # 是否仅对主要角色进行检测
    main_characters_only: true
    # 主要角色重要性阈值(0-1)
    importance_threshold: 0.3
    # 检测严重程度
    severity: "medium"

  # 情节连贯性检测
  plot_coherence:
    # 连贯性阈值，低于此值视为情节断裂
    coherence_threshold: 0.3
    # 检测严重程度
    severity: "high"

  # 未解决悬念检测
  unresolved_suspense:
    # 检测严重程度
    severity: "high"

  # 逻辑矛盾检测
  contradiction:
    # 检测严重程度
    severity: "critical"

# 角色弧线检测配置
character_arc_detection:
  # 主要角色重要性阈值(0-1)
  importance_threshold: 0.3
  # 角色弧线质量阈值(0-1)，低于此值视为问题
  quality_threshold: 0.6
  # 情感突变阈值，高于此值视为情感剧烈变化
  emotion_change_threshold: 1.2

# 情感曲线检测配置
emotion_curve_detection:
  # 情感平坦判定阈值
  flatness_threshold: 0.15
  # 情感高潮强度阈值
  peak_intensity_threshold: 0.7
  # 情感高潮数量阈值
  min_peaks: 1
  # 情感低谷数量阈值
  min_valleys: 1

# 建议生成配置
suggestion_generation:
  # 最大建议数量
  max_suggestions: 10
  # 建议优先级
  priorities:
    critical: 1.0
    high: 0.8
    medium: 0.5
    low: 0.3
  # 是否生成修复建议
  generate_fixes: true

# 可视化配置
visualization:
  # 是否启用可视化
  enabled: true
  # 可视化图表类型
  chart_types:
    - emotion_curve
    - character_arc
    - plot_density
  # 输出目录
  output_dir: "reports/sandbox"

# 分析深度配置
analysis_depth:
  # 是否进行深度分析
  enable_deep_analysis: true
  # 是否使用知识图谱
  use_knowledge_graph: true
  # 是否分析隐含剧情
  analyze_implicit_plot: true
  
# 缓存配置
caching:
  # 是否启用缓存
  enable_cache: true
  # 缓存目录
  cache_dir: "cache/sandbox"
  # 缓存过期时间（小时）
  expiration_hours: 24

# 质量评分配置
quality_scoring:
  # 各部分在总评分中的权重
  weights:
    plot_holes: 0.4
    character_consistency: 0.3
    emotional_flow: 0.3
  
  # 减分系数
  penalties:
    plot_hole: 0.05       # 每个剧情漏洞减分
    character_problem: 0.1 # 每个角色问题减分

# 可视化配置
visualization:
  # 图表尺寸
  figure_size: [12, 8]
  # 情感曲线颜色
  colors:
    positive: "green"
    negative: "red"
    neutral: "gray"
  # 问题标记样式
  markers:
    critical: ["rx", 12]  # 符号, 大小
    high: ["r^", 10]
    medium: ["yo", 8]
    low: ["bo", 6] 