"""
配置模块

包含项目各组件的配置和常量定义。
"""

from .constants import (
    MAX_EMOTION_DELTA,
    MIN_EMOTION_VARIATION,
    MIN_SCENES_FOR_CHECK,
    MAX_VISUAL_DELTA,
    MIN_VISUAL_CONTRAST,
    MAX_CONFLICT_DELTA,
    CONFLICT_SCENE_RATIO,
    NARRATIVE_POSITIONS,
    NARRATIVE_MIN_CLIMAX_INTENSITY,
    NARRATIVE_MAX_RESOLUTION_INTENSITY,
    EMOTION_TYPES,
    EMOTION_INTENSITY_RANGE,
    MEMORY_TRIGGER_TEMPLATES,
)

__all__ = [
    'MAX_EMOTION_DELTA',
    'MIN_EMOTION_VARIATION',
    'MIN_SCENES_FOR_CHECK',
    'MAX_VISUAL_DELTA',
    'MIN_VISUAL_CONTRAST',
    'MAX_CONFLICT_DELTA',
    'CONFLICT_SCENE_RATIO',
    'NARRATIVE_POSITIONS',
    'NARRATIVE_MIN_CLIMAX_INTENSITY',
    'NARRATIVE_MAX_RESOLUTION_INTENSITY',
    'EMOTION_TYPES',
    'EMOTION_INTENSITY_RANGE',
    'MEMORY_TRIGGER_TEMPLATES',
] 