# 动态强度调节器配置文件
# 控制情感强度、冲突激烈度和视觉刺激强度的实时调整

# 用户偏好配置
user_preferences:
  # 全局预设
  global_presets:
    balanced: 
      emotion_intensity: 1.0    # 标准强度
      conflict_intensity: 1.0   # 标准冲突强度
      visual_intensity: 1.0     # 标准视觉刺激
    subtle:
      emotion_intensity: 0.8    # 降低情感强度
      conflict_intensity: 0.7   # 降低冲突强度
      visual_intensity: 0.8     # 降低视觉刺激
    intense:
      emotion_intensity: 1.2    # 提高情感强度
      conflict_intensity: 1.3   # 提高冲突强度
      visual_intensity: 1.2     # 提高视觉刺激
    dramatic:
      emotion_intensity: 1.3    # 显著提高情感强度
      conflict_intensity: 1.4   # 显著提高冲突强度
      visual_intensity: 1.2     # 提高视觉刺激
    calm:
      emotion_intensity: 0.7    # 显著降低情感强度
      conflict_intensity: 0.6   # 显著降低冲突强度
      visual_intensity: 0.8     # 降低视觉刺激
  
  # 默认配置
  default_preset: "balanced"
  
  # 自适应调整
  adaptive_adjustment:
    enabled: true                # 是否启用自适应调整
    learning_rate: 0.05          # 学习率（调整速度）
    history_window: 10           # 历史窗口大小
    min_samples: 5               # 最小样本数量

# 情感强度调节
emotion_intensity:
  # 强度调节因子
  adjustment_factors:
    text_intensity: 0.4          # 文本情感强度权重
    dialog_intensity: 0.3        # 对话情感强度权重
    action_intensity: 0.3        # 动作情感强度权重
  
  # 情感类型特定调节
  type_specific:
    joy: 1.0                     # 喜悦情感调节因子
    sadness: 1.1                 # 悲伤情感调节因子
    anger: 1.2                   # 愤怒情感调节因子
    fear: 1.15                   # 恐惧情感调节因子
    surprise: 1.05               # 惊讶情感调节因子
    disgust: 0.95                # 厌恶情感调节因子
  
  # 峰值调节
  peak_adjustment:
    enabled: true                # 是否启用峰值调节
    peak_boost: 1.2              # 峰值增强因子
    valley_reduction: 0.9        # 低谷减弱因子
    transition_smoothing: 0.8    # 过渡平滑因子

# 冲突激烈度调节
conflict_intensity:
  # 冲突元素权重
  element_weights:
    dialog_confrontation: 0.35   # 对话冲突权重
    action_conflict: 0.4         # 动作冲突权重
    tension_build: 0.25          # 紧张感积累权重
  
  # 冲突类型调节
  type_adjustment:
    verbal: 0.9                  # 言语冲突调节因子
    physical: 1.1                # 物理冲突调节因子
    emotional: 1.0               # 情感冲突调节因子
    psychological: 1.05          # 心理冲突调节因子
  
  # 叙事结构调节
  narrative_adjustment:
    rising_action: 1.1           # 上升动作调节因子
    climax: 1.3                  # 高潮调节因子
    falling_action: 0.9          # 下降动作调节因子
    resolution: 0.8              # 解决调节因子

# 视觉刺激强度调节
visual_intensity:
  # 视觉元素权重
  element_weights:
    movement: 0.3                # 动作幅度权重
    color_contrast: 0.25         # 色彩对比权重
    scene_transitions: 0.2       # 场景转换权重
    facial_expressions: 0.25     # 面部表情权重
  
  # 视觉风格调节
  style_adjustment:
    fast_paced: 1.2              # 快节奏场景调节因子
    slow_paced: 0.9              # 慢节奏场景调节因子
    high_contrast: 1.15          # 高对比度场景调节因子
    low_contrast: 0.85           # 低对比度场景调节因子

# 动态调整规则
adjustment_rules:
  # 连续场景调整
  consecutive_scenes:
    max_similar_intensity: 3     # 最大连续相似强度场景数
    variation_threshold: 0.15    # 变化阈值
    forced_variation: 0.2        # 强制变化幅度
  
  # 情感变化速率限制
  rate_limiting:
    max_increase_rate: 0.3       # 最大增加速率
    max_decrease_rate: 0.25      # 最大减少速率
    smoothing_window: 2          # 平滑窗口大小
  
  # 叙事节点特殊调整
  narrative_nodes:
    introduction_factor: 0.9     # 引入因子
    buildup_factor: 1.05         # 铺垫因子
    climax_factor: 1.25          # 高潮因子
    resolution_factor: 0.85      # 解决因子

# 持久化配置
persistence:
  save_user_prefs: true          # 是否保存用户偏好
  prefs_file: "user_intensity_prefs.json"  # 用户偏好文件
  history_tracking: true         # 是否记录历史调整
  history_file: "intensity_adjustment_history.json"  # 历史文件

# 反馈学习配置
feedback_learning:
  enabled: true                  # 是否启用反馈学习
  positive_reinforcement: 0.1    # 正面反馈强化系数
  negative_reinforcement: 0.15   # 负面反馈强化系数
  neutral_decay: 0.01            # 中性衰减系数
  min_confidence: 0.6            # 最小置信度 