# 情感节奏调节配置文件
# 控制场景节奏调整参数和预设模式

# 情感强度调整参数
intensity_pacing:
  # 高情感强度场景
  high_intensity:
    factor: 1.3                # 高情感强度延长因子
    threshold: 0.8              # 高强度阈值
    max_extension: 0.5          # 最大延长比例
  
  # 中等情感强度场景
  medium_intensity:
    factor: 1.0                # 中情感强度因子
    threshold_low: 0.4          # 中强度下限
    threshold_high: 0.8         # 中强度上限
  
  # 低情感强度场景
  low_intensity:
    factor: 0.7                # 低情感强度缩短因子
    threshold: 0.4              # 低强度阈值
    min_duration: 0.7           # 最小持续时间比例

# 根据情感类型调整参数
emotion_type_adjustment:
  悲伤: 1.2                     # 悲伤情感场景延长因子
  喜悦: 0.9                     # 喜悦情感场景缩短因子
  紧张: 0.8                     # 紧张情感场景缩短因子
  恐惧: 0.85                    # 恐惧情感场景缩短因子
  愤怒: 0.95                    # 愤怒情感场景微缩因子
  惊讶: 1.1                     # 惊讶情感场景延长因子
  中性: 1.0                     # 中性情感场景保持不变

# 场景连贯性保证
coherence:
  max_delta: 0.15              # 相邻场景最大变化率
  enforce_continuity: true      # 是否强制连续性
  smooth_transitions: true      # 平滑过渡

# 场景持续时间约束
scene_constraints:
  min_duration: 0.8             # 最小场景持续时间(秒)
  max_duration: 15.0            # 最大场景持续时间(秒)

# 情感节奏模式预设
rhythm_patterns:
  # 情感渐强模式 - 让情感逐渐增强，适合有明确高潮的内容
  emotional_crescendo:
    start_factor: 0.8           # 起始调整因子（加速）
    end_factor: 1.2             # 结束调整因子（减速）
    curve: "linear"             # 变化曲线类型
  
  # 情感波浪模式 - 创造节奏韵律，保持观众兴趣
  emotional_wave:
    amplitude: 0.2              # 波浪幅度
    frequency: 2                # 波浪频率
    base_factor: 1.0            # 基础调整因子
  
  # 情感焦点模式 - 突出高情感场景，加速其他部分
  emotional_focus:
    regular_factor: 0.85        # 常规场景调整因子
    focus_factor: 1.25          # 焦点场景调整因子
    focus_range: 0.2            # 焦点影响范围（百分比）

# 情感-节奏关系规则
# 每0.1情感强度差异对应5%时长变化
emotion_rules:
  intensity_delta_rule: 0.05    # 每0.1情感强度差异对应的时长变化率
  max_variance: 0.15            # 相邻场景最大长度变化率
  
  # 高潮检测参数
  climax_detection:
    threshold: 0.75             # 高潮情感强度阈值
    min_prominence: 0.2         # 最小突出度
    extension_factor: 1.5       # 高潮场景延长因子

# 情感节奏类型和应用场景
rhythm_types:
  gradual:                      # 渐进式节奏
    description: "情感强度逐渐变化，适合叙事性内容"
    preferred_emotion_flow: "ascending"
  
  alternating:                  # 交替式节奏
    description: "快慢交替，避免观众疲劳"
    preferred_emotion_flow: "wave"
  
  punctuated:                   # 强调式节奏
    description: "突出重点场景，加速次要场景"
    preferred_emotion_flow: "peaks"
  
  crescendo:                    # 渐强式节奏
    description: "逐渐增强情感强度和展示时长"
    preferred_emotion_flow: "ascending_steep"

# 调试设置
debug:
  log_adjustments: true         # 记录节奏调整
  log_level: "info"             # 日志级别
  visualize_rhythm: false       # 是否可视化节奏 