# 语言检测引擎配置

# 字符集配置
character_sets:
  zh:
    ranges: 
      - [0x4E00, 0x9FFF]  # 基本汉字
      - [0x3400, 0x4DBF]  # 扩展A
    weight: 1.0
  en:
    ranges:
      - [0x0041, 0x005A]  # 大写英文
      - [0x0061, 0x007A]  # 小写英文
    weight: 1.0

# 编码检测配置
encoding_detection:
  default: "utf-8"
  fallback: "gbk"
  check_bom: true

# 特征提取配置
feature_extraction:
  use_ngrams: true
  ngram_range: [1, 2]
  normalize: true
  
# 性能优化
performance:
  cache_size: 1000
  batch_size: 100
  
# 日志配置
logging:
  level: "INFO"
  file: "logs/language_detector.log" 