# 内存资源熔断阈值配置
# VisionAI-ClipsMaster 内存资源管理

# 多级熔断阈值定义和对应动作
fuse_levels:
  - level: "WARNING"           # 初级熔断
    threshold: 85              # 内存使用百分比阈值
    actions:                   # 执行的动作列表
      - "clear_temp_files"     # 清理临时文件
      - "reduce_log_verbosity" # 减少日志详细程度
      - "pause_background_tasks" # 暂停后台任务
      - "reduce_cache_size"    # 减少缓存大小

  - level: "CRITICAL"          # 中级熔断
    threshold: 95              # 内存使用百分比阈值
    actions:
      - "unload_noncritical_shards" # 卸载非关键分片
      - "degrade_quality"           # 降低质量
      - "flush_memory_cache"        # 清空内存缓存
      - "switch_to_lightweight_models" # 切换到轻量级模型

  - level: "EMERGENCY"         # 紧急熔断
    threshold: 98              # 内存使用百分比阈值
    actions:
      - "kill_largest_process" # 杀死最大进程
      - "force_gc"             # 强制垃圾回收
      - "disable_features"     # 禁用特性
      - "activate_survival_mode" # 激活生存模式

# 熔断检测参数
detection:
  check_interval_seconds: 5.0  # 检测间隔(秒)
  stabilize_seconds: 30.0      # 稳定时间(秒)，在此时间内不重复触发同级熔断
  recovery_threshold: 70       # 恢复阈值，低于此值时恢复正常模式
  prediction_window: 60        # 预测窗口(秒)，用于趋势分析
  grace_duration: 15           # 宽限期(秒)，触发熔断后的冷却期

# 资源监控配置
monitoring:
  track_gpu_memory: true       # 是否监控GPU内存
  track_process_memory: true   # 是否监控进程内存
  track_swap_usage: true       # 是否监控交换区使用
  enable_prediction: true      # 启用预测
  log_resource_usage: true     # 记录资源使用
  alert_channels:              # 警报渠道
    - "console"                # 控制台输出
    - "log_file"               # 日志文件
    - "status_api"             # 状态API

# 动作配置详细参数
action_params:
  clear_temp_files:
    directories:               # 要清理的临时目录
      - "${TEMP}/visionai_clips_temp"
      - "${CACHE}/visionai_render_cache"
    file_patterns:             # 文件模式
      - "*.tmp"
      - "*.temp"
      - "*.bak"
    max_file_age_hours: 2      # 最大文件保留时间(小时)
  
  reduce_log_verbosity:
    target_level: "WARNING"    # 目标日志级别
    restore_after_recovery: true # 恢复后是否恢复原日志级别
  
  unload_noncritical_shards:
    shards:                    # 可卸载的非关键分片
      - "subtitle_generator"   # 字幕生成器
      - "effect_previewer"     # 特效预览
      - "auxiliary_models"     # 辅助模型
    keep_essential: true       # 保留必要组件
  
  degrade_quality:
    render_quality: "medium"   # 渲染质量
    preview_resolution: "720p" # 预览分辨率
    playback_quality: "low"    # 播放质量
  
  kill_largest_process:
    exclude_processes:         # 排除进程列表
      - "visionai_core"        # 核心进程
      - "system"               # 系统进程
    max_memory_percent: 20     # 最大内存百分比
    warn_before_kill: true     # 杀死前警告
  
  force_gc:
    aggressive: true           # 激进模式
    clear_module_caches: true  # 清除模块缓存
    run_times: 3               # 运行次数

# 恢复策略
recovery:
  auto_recover: true           # 是否自动恢复
  step_recovery: true          # 阶梯式恢复
  recovery_delay: 60           # 恢复延迟(秒)
  verify_stability: true       # 验证稳定性
  restore_settings: true       # 恢复设置

# 告警设置
alerts:
  notify_user: true            # 通知用户
  show_toast: true             # 显示toast
  log_to_file: true            # 记录到文件
  send_telemetry: false        # 发送遥测数据
  error_count_threshold: 3     # 错误计数阈值 