# VisionAI-ClipsMaster 模型配置文件
# 双模型系统配置 (Mistral-7B英文 + Qwen2.5-7B中文)

# 可用模型列表
models:
  mistral-7b-en:
    name: "Mistral-7B English Model"
    language: "en"
    path: "models/mistral/quantized/Q2_K.gguf"
    quantization_level: "Q2_K"
    memory_requirement: 2800  # MB - 优化为4GB设备
    context_length: 4096
    description: "英文剧本重构和字幕生成专用模型（4GB内存优化）"

  qwen2.5-7b-zh:
    name: "Qwen2.5-7B Chinese Model"
    language: "zh"
    path: "models/qwen/quantized/Q2_K.gguf"
    quantization_level: "Q2_K"
    memory_requirement: 2800  # MB - 优化为4GB设备
    context_length: 4096
    description: "中文剧本重构和字幕生成专用模型（4GB内存优化）"

# 基础模型配置（向后兼容）
base_models:
  en:
    name: "mistral-7b-en"
    path: "models/mistral/quantized/Q2_K.gguf"
    quantization_level: Q2_K
  zh:
    name: "qwen2.5-7b-zh"
    path: "models/qwen/quantized/Q2_K.gguf"
    quantization_level: Q2_K

# SRL模型配置
srl_models:
  en:
    name: "structured-prediction-srl-bert"
    path: "https://storage.googleapis.com/allennlp-public-models/structured-prediction-srl-bert.2020.12.15.tar.gz"
    fallback_enabled: true
  zh:
    name: "chinese-bert-wwm-ext-srl"
    path: "hfl/chinese-bert-wwm-ext"  # 实际项目中应替换为专门的中文SRL模型
    fallback_enabled: true

# 量化配置
quantization:
  available_levels:
    Q2_K:
      memory_usage: 2800  # MB
      quality_score: 72.3
      description: "最激进量化，内存危急时使用"
      use_case: "emergency"
    Q4_K_M:
      memory_usage: 4100  # MB
      quality_score: 85.6
      description: "标准量化，平衡性能和质量"
      use_case: "normal"
    Q5_K:
      memory_usage: 6300  # MB
      quality_score: 91.2
      description: "高质量量化，高配设备使用"
      use_case: "performance"

  default_level: "Q2_K"  # 4GB内存设备默认使用Q2_K量化
  adaptive_quantization: true  # 根据内存自动调整量化等级

  # 内存自适应量化策略
  memory_adaptive_levels:
    "<=3.8GB": "Q2_K"    # 4GB设备（预留0.2GB系统内存）
    "<=6.0GB": "Q4_K_M"  # 6GB设备
    ">6.0GB": "Q5_K"     # 高配设备

# 内存限制配置
memory_limits:
  max_total_memory: 3800  # MB，为4GB设备预留200MB系统内存
  model_memory_limit: 3500  # MB，单个模型最大内存
  cache_memory_limit: 200   # MB，缓存最大内存
  emergency_threshold: 3600 # MB，紧急释放内存阈值

  # 内存监控配置
  monitoring:
    check_interval: 5  # 秒，内存检查间隔
    warning_threshold: 0.85  # 内存使用率警告阈值
    critical_threshold: 0.95  # 内存使用率危险阈值

# 模型加载策略
loading_strategy:
  max_memory_usage: 3800  # MB，确保峰值内存不超过4GB
  dynamic_unloading: true  # 启用动态卸载
  batch_size: 8  # 小批量处理以节省内存
  preload_models: false  # 不预加载模型，按需加载
  model_offloading: true  # 启用模型卸载

# 性能优化配置
optimization:
  cpu_threads: 4  # CPU线程数
  compute_type: int8  # 使用int8计算以降低内存占用
  context_size: 2048  # 上下文窗口大小
  enable_gpu_acceleration: false  # 4GB设备通常无独显
  use_memory_mapping: true  # 使用内存映射减少内存占用

# 模型切换策略
model_switch:
  preload_threshold: 0.8  # 当某语言占比超过80%时预加载
  cache_size: 200  # 模型缓存大小(MB)，减少以适配4GB设备
  switch_delay: 1.5  # 最大切换延迟(秒)
  intelligent_switching: true  # 智能切换，基于内容分析
  fallback_model: "qwen2.5-7b-zh"  # 默认回退模型

# 语言检测配置
language_detection:
  threshold: 0.7  # 语言检测置信度阈值
  mixed_content_strategy: "dominant_language"  # 混合内容处理策略
  fallback_language: "zh"  # 检测失败时的默认语言

# 剧本重构配置
screenplay_reconstruction:
  max_input_length: 8000  # 最大输入字符数
  target_compression_ratio: 0.6  # 目标压缩比例
  preserve_key_scenes: true  # 保留关键场景
  maintain_narrative_flow: true  # 保持叙事流畅性

# 训练配置
training:
  batch_size: 4  # 训练批次大小
  learning_rate: 1e-5  # 学习率
  max_epochs: 10  # 最大训练轮数
  validation_split: 0.2  # 验证集比例

# 导出配置
export:
  jianying_compatibility: true  # 剪映兼容性
  timeline_precision: 0.5  # 时间轴精度（秒）
  video_format_support: ["mp4", "avi", "mov", "mkv", "flv"]

# 系统配置
system:
  log_level: "INFO"
  enable_debug: false
  temp_dir: "temp/"
  cache_dir: "cache/"
  backup_enabled: true