# VisionAI-ClipsMaster 监控指标定义
# 适用于双模型架构和低资源设备(4GB内存/无GPU)

version: "1.1"
description: "VisionAI-ClipsMaster监控指标配置"

# 系统资源指标
system_metrics:
  # 内存相关指标
  - name: "total_memory"
    desc: "系统总内存使用率"
    unit: "%"
    alert_threshold: 95  # 总内存使用率警告阈值
    critical_threshold: 98  # 严重警告阈值
    collect_interval: 5s  # 采集间隔
    retention: "7d"  # 保留时间

  - name: "process_rss"
    desc: "进程实际内存"
    unit: "MB"
    alert_threshold: 3800  # 4GB设备限制
    critical_threshold: 3900  # 紧急限制
    collect_interval: 5s
    retention: "7d"

  - name: "process_rss_percent"
    desc: "进程内存占比"
    unit: "%"
    alert_threshold: 85  # 占比警告阈值
    critical_threshold: 95
    collect_interval: 5s
    retention: "7d"

  # CPU相关指标
  - name: "cpu_usage"
    desc: "CPU使用率"
    unit: "%"
    alert_threshold: 85
    critical_threshold: 95
    collect_interval: 5s
    retention: "7d"

# 模型加载和运行指标
model_metrics:
  # 分片缓存指标
  - name: "shard_cache"
    desc: "分片缓存内存"
    unit: "MB"
    alert_threshold: 1500  # 分片缓存最大允许值
    critical_threshold: 1800
    collect_interval: 10s
    retention: "7d"

  - name: "active_model_memory"
    desc: "当前加载模型内存"
    unit: "MB"
    alert_threshold: 3000
    critical_threshold: 3500
    collect_interval: 10s
    retention: "7d"
    
  - name: "model_load_time"
    desc: "模型加载时间"
    unit: "ms"
    alert_threshold: 10000  # 10秒
    critical_threshold: 30000  # 30秒
    collect_interval: "on_demand"  # 按需采集
    retention: "30d"

  - name: "model_inference_time"
    desc: "模型推理时间"
    unit: "ms"
    alert_threshold: 2000  # 2秒
    critical_threshold: 5000  # 5秒
    collect_interval: "on_demand"
    retention: "7d"

# 缓存性能指标
cache_metrics:
  - name: "cache_hit_rate"
    desc: "缓存命中率"
    unit: "%"
    alert_threshold: 60  # 低于此值警告
    critical_threshold: 40  # 低于此值严重警告
    collect_interval: 1m
    retention: "7d"

  - name: "cache_eviction_rate"
    desc: "缓存淘汰率"
    unit: "evictions/min"
    alert_threshold: 30  # 每分钟淘汰次数阈值
    critical_threshold: 60
    collect_interval: 1m
    retention: "7d"

  - name: "cache_fragment_count"
    desc: "缓存碎片数量"
    unit: "个"
    alert_threshold: 100
    critical_threshold: 200
    collect_interval: 5m
    retention: "7d"

  - name: "preheater_prediction_accuracy"
    desc: "预热预测准确率"
    unit: "%"
    alert_threshold: 60  # 低于此值警告
    critical_threshold: 40
    collect_interval: 1h
    retention: "30d"

# 容灾恢复指标
recovery_metrics:
  - name: "cache_integrity"
    desc: "缓存完整性评分"
    unit: "%"
    alert_threshold: 90  # 低于此值警告
    critical_threshold: 80  # 低于此值严重警告
    collect_interval: 30m
    retention: "30d"

  - name: "recovery_time"
    desc: "缓存恢复耗时"
    unit: "ms"
    alert_threshold: 5000  # 5秒
    critical_threshold: 15000  # 15秒
    collect_interval: "on_demand"
    retention: "30d"

  - name: "recovery_count"
    desc: "每日恢复次数"
    unit: "次/天"
    alert_threshold: 5  # 每天恢复超过5次警告
    critical_threshold: 10
    collect_interval: 1h
    retention: "90d"

# 应用性能指标
application_metrics:
  - name: "api_latency"
    desc: "API响应时间"
    unit: "ms"
    alert_threshold: 1000  # 1秒
    critical_threshold: 3000  # 3秒
    collect_interval: "on_request"
    retention: "7d"

  - name: "error_rate"
    desc: "错误率"
    unit: "%"
    alert_threshold: 5
    critical_threshold: 10
    collect_interval: 5m
    retention: "7d"

  - name: "active_connections"
    desc: "活跃连接数"
    unit: "个"
    alert_threshold: 100
    critical_threshold: 200
    collect_interval: 10s
    retention: "3d"

# 模型特定指标
model_specific_metrics:
  # 中文模型 (Qwen2.5-7B)
  - name: "qwen_memory"
    desc: "Qwen模型内存"
    unit: "MB"
    alert_threshold: 4000
    critical_threshold: 4100
    collect_interval: 10s
    retention: "7d"

  - name: "qwen_latency"
    desc: "Qwen模型延迟"
    unit: "ms"
    alert_threshold: 1500
    critical_threshold: 3000
    collect_interval: "on_request"
    retention: "7d"

  # 英文模型 (Mistral-7B)
  - name: "mistral_memory"
    desc: "Mistral模型内存"
    unit: "MB"
    alert_threshold: 4000
    critical_threshold: 4100
    collect_interval: 10s
    retention: "7d"
    enabled: false  # 默认禁用(未下载)

  - name: "mistral_latency"
    desc: "Mistral模型延迟"
    unit: "ms"
    alert_threshold: 1500
    critical_threshold: 3000
    collect_interval: "on_request"
    retention: "7d"
    enabled: false  # 默认禁用(未下载)

# 数据导出和历史记录配置
export_config:
  auto_export: true
  interval: "1d"
  formats: ["json", "csv"]
  retention_days: 90
  path: "logs/metrics_export" 