# 定义常见的叙事类型与结构
# 用于生成不同风格的短剧混剪

# 常规叙事模式
standard_narrative:
  name: "标准叙事结构"
  description: "经典的开端-发展-高潮-结局结构"
  beat_distribution:
    exposition: 0.20      # 开场铺垫
    rising_action: 0.40   # 冲突发展
    climax: 0.25          # 高潮
    resolution: 0.15      # 结局
  transition_rules:
    - from: "exposition"
      to: "rising_action"
      required: true
    - from: "rising_action"
      to: "climax"
      required: true
    - from: "climax"
      to: "resolution"
      required: true
  min_beats: 4
  target_duration: 60     # 目标时长(秒)

# 快节奏紧张型
tension_driven:
  name: "紧张型叙事"
  description: "快节奏冲突驱动，强调戏剧冲突和悬疑"
  beat_distribution:
    exposition: 0.10      # 简短开场
    rising_action: 0.50   # 大量冲突
    climax: 0.30          # 扩大高潮
    resolution: 0.10      # 简短结局
  transition_rules:
    - from: "exposition"
      to: "rising_action"
      required: true
    - from: "rising_action"
      to: "climax"
      required: true
    - from: "climax"
      to: "resolution"
      required: true
    - from: "rising_action"
      to: "rising_action"
      max_consecutive: 3  # 最多连续3个rising_action
  min_beats: 5
  target_duration: 45     # 目标时长(秒)

# 情感主导型
emotional_focus:
  name: "情感主导型"
  description: "强调人物情感变化，关注情感起伏和内心世界"
  beat_distribution:
    exposition: 0.25      # 充分铺垫人物背景
    rising_action: 0.35   # 情感变化过程
    climax: 0.20          # 情感高潮
    resolution: 0.20      # 充分结局
  transition_rules:
    - from: "exposition"
      to: "rising_action"
      required: true
    - from: "rising_action"
      to: "climax"
      required: true
    - from: "resolution"
      to: "climax" 
      required: false     # 允许结局后回顾高潮(闪回)
  min_beats: 4
  target_duration: 70     # 目标时长(秒)

# 悬疑反转型
twist_ending:
  name: "悬疑反转型"
  description: "设置悬疑氛围，结尾有重大反转"
  beat_distribution:
    exposition: 0.20
    rising_action: 0.35
    climax: 0.15
    resolution: 0.30      # 扩大结局比重(包含反转)
  transition_rules:
    - from: "resolution"
      to: "exposition"
      required: false     # 允许结局回到开头(循环结构)
    - from: "resolution"
      to: "climax"
      required: false     # 允许在结局后安排另一个高潮(反转)
  min_beats: 5
  target_duration: 65     # 目标时长(秒)

# 特效展示型
visual_spectacle:
  name: "视觉奇观型"
  description: "强调视觉效果和场面震撼，适合动作或奇幻题材"
  beat_distribution:
    exposition: 0.15      # 简短铺垫
    rising_action: 0.30   # 场景渐进
    climax: 0.40          # 大量高潮场景
    resolution: 0.15      # 简短结局
  transition_rules:
    - from: "climax"
      to: "climax"
      max_consecutive: 2  # 允许连续高潮场景
  min_beats: 4
  target_duration: 55     # 目标时长(秒)

# 人物中心型
character_centered:
  name: "人物中心型"
  description: "聚焦人物成长或变化，注重人物塑造"
  beat_distribution:
    exposition: 0.30      # 大量人物铺垫
    rising_action: 0.30   # 人物变化过程
    climax: 0.20          # 人物转变高潮
    resolution: 0.20      # 人物结局
  transition_rules:
    - from: "exposition"
      to: "exposition"
      max_consecutive: 2  # 允许多段铺垫
  min_beats: 4
  target_duration: 75     # 目标时长(秒)

# 喜剧型
comedy_pattern:
  name: "喜剧型"
  description: "强调幽默元素和包袱设置，节奏轻快"
  beat_distribution:
    exposition: 0.20
    rising_action: 0.45   # 更多的包袱铺设
    climax: 0.20
    resolution: 0.15
  transition_rules:
    - from: "rising_action"
      to: "climax"
      to: "rising_action"
      required: false     # 允许高潮后再次进入铺设，形成多个包袱
  min_beats: 5
  target_duration: 50     # 目标时长(秒)

# 对话驱动型
dialogue_driven:
  name: "对话驱动型"
  description: "以精彩对白为主，适合情感和戏剧性内容"
  beat_distribution:
    exposition: 0.25
    rising_action: 0.30
    climax: 0.25
    resolution: 0.20
  min_beats: 6            # 需要更多节拍保证对话完整性
  target_duration: 80     # 目标时长(秒) 