# 参数矩阵配置文件
# 定义不同剧本风格的参数矩阵

# 全局设置
global:
  min_segment_duration: 1.5     # 最小片段时长(秒)
  max_total_duration: 120       # 最大总时长(秒)
  min_total_duration: 20        # 最小总时长(秒)
  target_duration: 60           # 目标总时长(秒)
  max_segments: 15              # 最大片段数

# 基础预设参数组
presets:
  # 默认平衡参数
  default:
    pace: 1.0                   # 节奏系数 (0.5-2.0)
    emotion_intensity: 0.7      # 情感强度 (0-1)
    subplot: 3                  # 支线数量 (0-5)
    cliffhanger_freq: 0.4       # 悬念频率 (0-1)
    resolution_delay: 0.5       # 悬念密度 (0-1)
    character_focus: 2          # 角色聚焦数量 (1-5)
    conflict_intensity: 0.6     # 冲突强度 (0-1)
    punchline_ratio: 0.15       # 金句保留比例 (0-0.3)
    context_preservation: 0.5   # 上下文保留度 (0-1)
    linearity: 0.7              # 线性叙事程度 (0-1, 0为高度非线性)
  
  # 快节奏预设 - 适合动作/冲突场景
  快节奏:
    pace: 1.3                   # 更快的节奏
    emotion_intensity: 0.8      # 较高情感强度
    subplot: 2                  # 减少支线，聚焦主线
    cliffhanger_freq: 0.6       # 较高悬念频率
    resolution_delay: 0.8       # 高悬念密度
    character_focus: 2          # 聚焦核心角色
    conflict_intensity: 0.8     # 高冲突强度
    punchline_ratio: 0.2        # 金句保留适中
    context_preservation: 0.4   # 减少上下文，增加节奏感
    linearity: 0.6              # 相对线性
  
  # 深度情感预设 - 适合情感/人物刻画
  深度情感:
    pace: 0.8                   # 较慢节奏
    emotion_intensity: 0.9      # 高情感强度
    subplot: 2                  # 集中情感线
    cliffhanger_freq: 0.3       # 低悬念频率
    resolution_delay: 0.4       # 低悬念密度
    character_focus: 1          # 单角色聚焦
    conflict_intensity: 0.7     # 中高冲突强度
    punchline_ratio: 0.15       # 金句保留适中
    context_preservation: 0.7   # 高上下文保留
    linearity: 0.8              # 高度线性
  
  # 悬念优先预设 - 适合悬疑/惊悚
  悬念优先:
    pace: 0.9                   # 中等节奏
    emotion_intensity: 0.6      # 中等情感强度
    subplot: 3                  # 多支线增加复杂性
    cliffhanger_freq: 0.8       # 高悬念频率
    resolution_delay: 0.9       # 最高悬念密度
    character_focus: 3          # 多角色视角
    conflict_intensity: 0.5     # 中等冲突强度
    punchline_ratio: 0.1        # 低金句保留
    context_preservation: 0.5   # 中等上下文保留
    linearity: 0.4              # 非线性叙事
  
  # 剧情紧凑预设 - 适合网剧/短剧
  剧情紧凑:
    pace: 1.2                   # 较快节奏
    emotion_intensity: 0.75     # 中高情感强度
    subplot: 1                  # 最少支线
    cliffhanger_freq: 0.5       # 中等悬念频率
    resolution_delay: 0.6       # 中高悬念密度
    character_focus: 2          # 双角色聚焦
    conflict_intensity: 0.75    # 高冲突强度
    punchline_ratio: 0.25       # 高金句保留
    context_preservation: 0.4   # 低上下文保留
    linearity: 0.85             # 高度线性
  
  # 复杂叙事预设 - 适合剧情复杂的长剧
  复杂叙事:
    pace: 0.7                   # 慢节奏
    emotion_intensity: 0.65     # 中等情感强度
    subplot: 5                  # 最多支线
    cliffhanger_freq: 0.4       # 中等悬念频率
    resolution_delay: 0.5       # 中等悬念密度
    character_focus: 4          # 多角色聚焦
    conflict_intensity: 0.65    # 中等冲突强度
    punchline_ratio: 0.1        # 低金句保留
    context_preservation: 0.8   # 高上下文保留
    linearity: 0.3              # 高度非线性

# 语言特定参数调整
language_adjustments:
  # 中文特定参数调整
  zh:
    context_preservation: 0.1   # 中文需要更高的上下文保留
    linearity: -0.1             # 中文通常线性度略低
    character_focus: 0.2        # 中文更关注角色
  
  # 英文特定参数调整
  en:
    emotion_intensity: 0.05     # 英文需要更高的情感强度
    punchline_ratio: 0.05       # 英文金句保留比例更高
    pace: 0.1                   # 英文节奏略快

# 参数合法范围
valid_ranges:
  pace: [0.5, 2.0]
  emotion_intensity: [0.0, 1.0]
  subplot: [0, 5]
  cliffhanger_freq: [0.0, 1.0]
  resolution_delay: [0.0, 1.0]
  character_focus: [1, 5]
  conflict_intensity: [0.0, 1.0]
  punchline_ratio: [0.0, 0.3]
  context_preservation: [0.0, 1.0]
  linearity: [0.0, 1.0]

# 参数权重（用于自适应调整）
param_weights:
  pace: 1.0
  emotion_intensity: 1.2        # 情感强度权重略高
  subplot: 0.8
  cliffhanger_freq: 1.1
  resolution_delay: 0.9
  character_focus: 1.0
  conflict_intensity: 1.2       # 冲突强度权重略高
  punchline_ratio: 0.7
  context_preservation: 1.0
  linearity: 0.8 