# 模式重要性评估配置文件
# 包含评估模式重要性的所有参数设置

# 评估指标配置
metrics:
  # 观众留存提升率
  audience_retention:
    weight: 0.25           # 在总评分中的权重
    threshold: 0.6         # 最低阈值，高于此值表示有显著影响
    description: "观众留存提升率"
    
  # 社交媒体传播系数  
  viral_coefficient:
    weight: 0.2
    threshold: 0.5
    description: "社交媒体传播系数"
    
  # 平台推荐权重
  recommendation_weight:
    weight: 0.15
    threshold: 0.55
    description: "平台推荐权重"
    
  # 情感强度指数
  emotional_intensity:
    weight: 0.25
    threshold: 0.65
    description: "情感强度指数"
    
  # 叙事结构合理性
  narrative_coherence:
    weight: 0.15
    threshold: 0.5
    description: "叙事结构合理性"

# 评估模型路径
model_paths:
  # 观众留存模型
  retention_model: "models/evaluation/retention_estimator.pkl"
  # 病毒传播模型
  virality_model: "models/evaluation/virality_estimator.pkl"
  # 推荐系统模型
  recommendation_model: "models/evaluation/recommendation_estimator.pkl"

# 评分阈值设置
thresholds:
  # 最低影响力分数，低于此值的模式被视为不重要
  min_impact_score: 0.6
  # 最低置信度，低于此值的评估结果不可靠
  min_confidence: 0.65
  # 突出显示阈值，高于此值的模式将被突出显示为关键模式
  highlight_threshold: 0.8

# 特征重要性配置
feature_importance:
  # 模式频率重要性
  frequency: 0.3
  # 位置重要性
  position: 0.15
  # 情感强度重要性
  sentiment: 0.25
  # 时长重要性
  duration: 0.1
  # 惊喜程度重要性
  surprise_level: 0.2

# 模式类型特定配置
pattern_types:
  # 开场模式
  opening:
    ideal_position: 0.0    # 理想位置（视频开始）
    position_tolerance: 0.2  # 位置容忍度
    min_duration: 1.5      # 最小时长（秒）
    max_duration: 5.0      # 最大时长（秒）
    
  # 高潮模式
  climax:
    ideal_position: 0.7    # 理想位置（视频70%处）
    position_tolerance: 0.15
    min_duration: 2.0
    max_duration: 8.0
    
  # 转场模式
  transition:
    ideal_position: 0.5    # 中间位置
    position_tolerance: 0.3
    min_duration: 0.5
    max_duration: 2.0
    
  # 结尾模式
  ending:
    ideal_position: 1.0    # 结尾
    position_tolerance: 0.2
    min_duration: 2.0
    max_duration: 6.0
    
  # 冲突模式
  conflict:
    ideal_position: 0.4
    position_tolerance: 0.2
    min_duration: 3.0
    max_duration: 10.0
    
  # 解决模式
  resolution:
    ideal_position: 0.8
    position_tolerance: 0.15
    min_duration: 2.0
    max_duration: 6.0

# 情感类型影响力配置
emotion_weights:
  joy: 0.8         # 喜悦
  surprise: 0.9    # 惊喜
  anger: 0.7       # 愤怒
  sadness: 0.6     # 悲伤
  fear: 0.7        # 恐惧
  disgust: 0.5     # 厌恶
  neutral: 0.3     # 中性

# 分析设置
analysis:
  # 最多返回的模式数量
  max_patterns: 20
  # 分组展示
  group_by_type: true
  # 详细分析级别 (basic, detailed, comprehensive)
  detail_level: "detailed"
  # 可视化设置
  visualization:
    enabled: true
    highlight_color: "#FF5733"  # 重要模式高亮颜色
    neutral_color: "#3498DB"    # 普通模式颜色
    chart_type: "radar"         # 图表类型：radar, bar, line
    
# 整合设置
integration:
  # 与剧本工程师模块整合
  screenplay_engineer:
    enabled: true
    # 自动将高分模式推荐给剧本生成器
    auto_recommend: true
    # 推荐阈值
    recommendation_threshold: 0.75
    
  # 与模式数据湖整合
  pattern_lake:
    enabled: true
    # 自动记录高评分模式
    auto_record: true
    # 记录阈值
    record_threshold: 0.7
    
  # 与用户界面整合
  ui:
    show_scores: true
    interactive_adjustment: true
    show_comparison: true 