# 模型量化层配置

# 注意力层配置
attention:
  bits: 8              # 位宽
  scheme: dynamic      # 量化方案 (dynamic/static)
  threshold: 0.1      # 精度阈值
  priority: high      # 优先级

# 嵌入层配置
embedding:
  bits: 4
  scheme: static
  threshold: 0.2
  priority: medium

# 前馈层配置
ffn:
  bits: 6
  scheme: dynamic
  threshold: 0.15
  priority: medium

# 全局配置
global:
  min_bits: 4         # 最小位宽
  max_bits: 8         # 最大位宽
  default_scheme: dynamic
  accuracy_threshold: 0.9
  performance_threshold: 0.8
  memory_threshold: 0.7 