# VisionAI-ClipsMaster 资源管理配置
# 用于低内存设备(4GB)的智能资源释放策略

resource_types:
  # 核心模型分片 - 模型层级动态卸载
  - name: "model_shards"
    description: "未激活的模型层"
    priority: 1            # 最高释放优先级
    max_retain_time: 300   # 5分钟未使用自动释放
    release_strategy: "lru_cache"
    release_threshold: 0.85  # 当内存使用超过85%时触发
    min_required_shards: 2  # 保留最少必要层数
  
  # 渲染缓存 - 视频帧处理缓冲
  - name: "render_cache"
    description: "视频帧渲染中间结果"
    priority: 2
    max_retain_time: 180   # 3分钟后释放
    release_strategy: "clear_all"
    compression_enabled: true  # 启用zlib压缩减少内存占用
  
  # 临时计算缓冲区
  - name: "temp_buffers"
    description: "临时计算结果和中间状态"
    priority: 3
    max_retain_time: 30    # 30秒后释放
    release_strategy: "immediate"
  
  # 音频数据缓存
  - name: "audio_cache"
    description: "音频波形分析缓存"
    priority: 4
    max_retain_time: 120   # 2分钟后释放
    compression_enabled: true
  
  # 非活跃模型权重缓存
  - name: "model_weights_cache"
    description: "不常用模型权重"
    priority: 5
    max_retain_time: 600   # 10分钟未使用自动卸载
    model_specific:
      # 中文模型配置 - 当前使用
      - model_id: "qwen2.5-7b-zh"
        min_required_layers: 4
        emergency_quantization: "Q2_K"  # 紧急情况下更激进量化
      
      # 英文模型配置 - 保留但暂不加载
      - model_id: "mistral-7b-en"
        auto_load: false   # 不自动加载
        defer_loading: true  # 按需加载
        cache_config_only: true  # 仅缓存配置不缓存权重

  # 字幕索引数据
  - name: "subtitle_index"
    description: "字幕预处理索引数据"
    priority: 6
    max_retain_time: 900   # 15分钟未使用自动释放
    incremental_release: true  # 支持部分释放

# 内存监控策略
monitoring:
  check_interval_seconds: 5   # 每5秒检查一次内存状态
  warning_threshold: 0.75     # 75%内存使用率发出警告
  emergency_threshold: 0.90   # 90%触发紧急释放
  recovery_actions:
    - action: "release_by_priority"
      trigger: "warning_threshold"
    - action: "aggressive_quantization"
      trigger: "emergency_threshold"
    - action: "pause_processing"
      trigger: "emergency_threshold" 

# 恢复策略
recovery:
  auto_reload_delay: 2000     # 资源释放后重新加载延迟(毫秒)
  progressive_loading: true   # 启用渐进式加载
  memory_reserve_mb: 512      # 保留512MB防止OOM

# 日志记录
logging:
  resource_events: true       # 记录资源释放/加载事件
  memory_snapshots: true      # 定期记录内存快照
  snapshot_interval: 60       # 每分钟记录一次内存使用情况 