# VisionAI-ClipsMaster 动态阈值调整规则配置
# 适用于根据系统负载自动调整监控阈值的规则

version: "1.0"
description: "阈值动态调整规则配置"

# 全局调整参数
global_settings:
  # 调整间隔时间
  adjustment_interval: 300  # 5分钟
  # 记录保留时间
  history_retention_days: 30

# 内存相关阈值调整规则
memory_adjustments:
  # 进程实际内存阈值调整 (系统负载 -> 阈值)
  process_rss:
    - load: 70   # 系统负载<70%
      value: 3800  # 阈值设为3800MB
    - load: 85   # 系统负载70%-85%
      value: 3500  # 阈值设为3500MB
    - load: 100  # 系统负载>85%
      value: 3200  # 阈值设为3200MB
      
  # 进程内存占比阈值调整
  process_rss_percent:
    - load: 70
      value: 85
    - load: 85
      value: 80
    - load: 100
      value: 75

# 缓存相关阈值调整规则
cache_adjustments:
  # 缓存淘汰率阈值调整
  cache_eviction_rate:
    - load: 60
      value: 20
    - load: 80
      value: 30
    - load: 100
      value: 50
      
  # 分片缓存内存阈值调整
  shard_cache:
    - load: 60
      value: 1800
    - load: 80
      value: 1500
    - load: 100
      value: 1200
      
  # 缓存命中率阈值调整（低于此值警告）
  cache_hit_rate:
    - load: 60
      value: 60
    - load: 80
      value: 50
    - load: 100
      value: 40

# 模型性能相关阈值调整规则
model_adjustments:
  # 模型加载时间阈值调整
  model_load_time:
    - load: 60
      value: 15000  # 15秒
    - load: 80
      value: 20000  # 20秒
    - load: 100
      value: 30000  # 30秒
      
  # 模型推理时间阈值调整
  model_inference_time:
    - load: 60
      value: 2000   # 2秒
    - load: 80
      value: 3000   # 3秒
    - load: 100
      value: 5000   # 5秒
      
  # 当前加载模型内存阈值调整
  active_model_memory:
    - load: 60
      value: 3500
    - load: 80
      value: 3000
    - load: 100
      value: 2800

# 模型特定阈值调整
model_specific_adjustments:
  # 中文模型 (Qwen2.5-7B)
  qwen_memory:
    - load: 70
      value: 4000
    - load: 85
      value: 3800
    - load: 100
      value: 3500
      
  # 英文模型 (Mistral-7B) - 目前未下载，但保留配置
  mistral_memory:
    - load: 70
      value: 4000
    - load: 85
      value: 3800
    - load: 100
      value: 3500
    enabled: false  # 默认禁用 