# 时间码精度配置
timecode_precision:
  # 时间码容差（秒）
  tolerance: 0.05
  
  # 精度级别
  precision_level: "high"  # low, medium, high, ultra
  
  # 对齐算法
  alignment_algorithm: "dtw"  # dtw, linear, adaptive
  
  # 帧率适配
  frame_rate_adaptation: true
  
  # 精度验证
  validation:
    enabled: true
    max_drift: 0.1  # 最大漂移（秒）
    auto_correction: true

# 不同精度级别的配置
precision_levels:
  low:
    tolerance: 0.2
    sample_rate: 10
  medium:
    tolerance: 0.1
    sample_rate: 25
  high:
    tolerance: 0.05
    sample_rate: 50
  ultra:
    tolerance: 0.01
    sample_rate: 100
