# VisionAI-ClipsMaster UI交互配置
# 界面设置、快捷键、主题、布局参数

# 基础UI配置
ui_config:
  version: "1.0.0"

  # 窗口设置
  window:
    default_width: 1200
    default_height: 800
    min_width: 800
    min_height: 600
    resizable: true
    center_on_screen: true
    remember_size: true
    remember_position: true

  # 启动设置
  startup:
    show_splash: true
    splash_duration: 3000  # 毫秒
    auto_check_updates: false
    restore_last_session: true
    startup_timeout: 5000  # 5秒启动超时

# 主题配置
themes:
  # 当前主题
  current_theme: "light"

  # 可用主题
  available_themes:
    - "light"
    - "dark"
    - "high_contrast"

  # 主题切换
  theme_switching:
    enabled: true
    real_time_preview: true
    require_restart: false
    animation_duration: 300  # 毫秒

  # 浅色主题
  light:
    name: "浅色主题"
    primary_color: "#007bff"
    secondary_color: "#6c757d"
    background_color: "#ffffff"
    surface_color: "#f8f9fa"
    text_color: "#333333"
    text_secondary: "#6c757d"
    border_color: "#dee2e6"
    hover_color: "#e9ecef"
    accent_color: "#e3f2fd"

  # 深色主题
  dark:
    name: "深色主题"
    primary_color: "#0d6efd"
    secondary_color: "#6c757d"
    background_color: "#212529"
    surface_color: "#343a40"
    text_color: "#ffffff"
    text_secondary: "#adb5bd"
    border_color: "#495057"
    hover_color: "#495057"
    accent_color: "#1e3a5f"

  # 高对比度主题
  high_contrast:
    name: "高对比度主题"
    primary_color: "#000000"
    secondary_color: "#666666"
    background_color: "#000000"
    surface_color: "#000000"
    text_color: "#ffffff"
    text_secondary: "#ffffff"
    border_color: "#ffffff"
    hover_color: "#ffffff"
    accent_color: "#ffffff"

# 字体配置
fonts:
  # 系统字体
  system_fonts:
    windows: "Microsoft YaHei UI"
    macos: "PingFang SC"
    linux: "Noto Sans CJK SC"

  # 字体大小
  font_sizes:
    small: 11
    normal: 13
    large: 15
    title: 16

  # 字体权重
  font_weights:
    normal: 400
    medium: 500
    bold: 700

# 布局配置
layout:
  # 主布局
  main_layout:
    sidebar_width: 250
    sidebar_collapsible: true
    toolbar_height: 40
    statusbar_height: 25

  # 面板配置
  panels:
    training_panel:
      default_visible: true
      resizable: true
      min_height: 200

    progress_dashboard:
      default_visible: true
      resizable: true
      min_height: 150

    log_viewer:
      default_visible: false
      resizable: true
      min_height: 100

# 快捷键配置
shortcuts:
  # 文件操作
  file_operations:
    new_project: "Ctrl+N"
    open_project: "Ctrl+O"
    save_project: "Ctrl+S"
    save_as: "Ctrl+Shift+S"
    exit: "Ctrl+Q"

  # 编辑操作
  edit_operations:
    undo: "Ctrl+Z"
    redo: "Ctrl+Y"
    copy: "Ctrl+C"
    paste: "Ctrl+V"
    select_all: "Ctrl+A"

  # 视图操作
  view_operations:
    toggle_sidebar: "F9"
    toggle_fullscreen: "F11"
    zoom_in: "Ctrl+Plus"
    zoom_out: "Ctrl+Minus"
    reset_zoom: "Ctrl+0"

  # 功能操作
  function_operations:
    start_processing: "F5"
    stop_processing: "Esc"
    switch_language: "Ctrl+L"
    toggle_theme: "Ctrl+T"
    show_settings: "Ctrl+Comma"

# 交互设置
interaction:
  # 鼠标设置
  mouse:
    double_click_interval: 500  # 毫秒
    hover_delay: 300            # 毫秒
    wheel_scroll_lines: 3

  # 键盘设置
  keyboard:
    key_repeat_delay: 500       # 毫秒
    key_repeat_rate: 30         # 每秒

  # 触摸设置（未来扩展）
  touch:
    enabled: false
    gesture_recognition: false

# 动画设置
animations:
  enabled: true
  duration: 250      # 毫秒
  easing: "ease_out"

  # 具体动画
  fade_in_duration: 200
  fade_out_duration: 150
  slide_duration: 300
  scale_duration: 200

# 通知设置
notifications:
  enabled: true
  position: "bottom_right"  # top_left, top_right, bottom_left, bottom_right
  duration: 5000           # 毫秒
  max_notifications: 3

  # 通知类型
  types:
    info: true
    warning: true
    error: true
    success: true

# 性能设置
performance:
  # 渲染设置
  rendering:
    vsync: true
    max_fps: 60
    hardware_acceleration: true

  # 内存设置
  memory:
    ui_memory_limit: 400     # MB
    cache_size: 50           # MB
    garbage_collection: true

  # 响应性设置
  responsiveness:
    ui_thread_priority: "normal"
    background_task_priority: "low"
    max_ui_freeze_time: 100  # 毫秒

# 可访问性设置
accessibility:
  enabled: true

  # 视觉辅助
  visual:
    high_contrast_mode: false
    large_text_mode: false
    reduce_motion: false

  # 键盘导航
  keyboard_navigation:
    tab_navigation: true
    arrow_key_navigation: true
    enter_activation: true

  # 屏幕阅读器支持
  screen_reader:
    enabled: false
    announce_changes: true

# 调试设置
debug:
  enabled: false
  show_debug_info: false
  log_ui_events: false
  performance_monitoring: false

# 国际化设置
i18n:
  # 当前语言
  current_language: "zh_CN"

  # 支持的语言
  supported_languages:
    - "zh_CN"  # 简体中文
    - "en_US"  # 英语

  # 语言切换
  language_switching:
    enabled: true
    require_restart: false
    auto_detect: true

  # 文本方向
  text_direction:
    rtl_support: false
    auto_direction: false

# 向后兼容设置
legacy:
  language: zh
  theme: light  # 改为light主题以保持一致性
  window_size:
    - 1200
    - 800
