# 版本配置文件
# 管理版本兼容性和相关功能设置

version_config_schema:
  compatibility:
    target_version:
      type: "str"
      pattern: "^\\d+\\.\\d+(\\.[\\d]+)?$"
      default: "3.0"
    check_updates:
      type: "bool"
      default: true
    update_interval:
      type: "int"
      min: 1
      max: 30
      default: 7
    auto_adapt:
      type: "bool"
      default: true
    fallback_enabled:
      type: "bool"
      default: true
  
  schemas:
    default_schema:
      type: "str"
      default: "jianying_v3.xsd"
    validation_level:
      type: "str"
      enum: ["strict", "normal", "loose"]
      default: "normal"
  
  features:
    required_nodes:
      type: "array"
      items:
        type: "str"
      default: ["project", "sequence", "video", "audio"]
    supported_features:
      type: "array"
      items:
        type: "str"
      default: ["multi_track", "effects_layer", "subtitle_track"]

# 版本定义
version_definitions:
  "3.1":
    description: "未来版本，实验性支持"
    schema: "jianying_v3.xsd"
    required_nodes:
      - "project"
      - "sequence"
      - "video"
      - "audio"
      - "metadata"
      - "effects"
      - "advanced_effects"
    supported_features:
      - "multi_track"
      - "effects_layer"
      - "subtitle_track"
      - "audio_effects"
      - "nested_sequences"
      - "advanced_effects"
      - "4k_resolution"
      - "hdr"
      - "3d_effects"
    compatible_with: []
  
  "3.0":
    description: "当前最新版本，支持4K处理"
    schema: "jianying_v3.xsd"
    required_nodes:
      - "project"
      - "sequence"
      - "video"
      - "audio"
      - "metadata"
      - "effects"
    supported_features:
      - "multi_track"
      - "effects_layer"
      - "subtitle_track"
      - "audio_effects"
      - "nested_sequences"
      - "advanced_effects"
    compatible_with: ["2.5", "2.0"]
  
  "2.5":
    description: "添加高级时间线格式"
    schema: "jianying_v2.xsd"
    required_nodes:
      - "project"
      - "sequence"
      - "video"
      - "audio"
      - "metadata"
    supported_features:
      - "multi_track"
      - "subtitle_track"
    unsupported_nodes:
      - "effects"
      - "nested_sequences"
    compatible_with: ["2.0"]
  
  "2.0":
    description: "添加元数据支持"
    schema: "jianying_v2.xsd"
    required_nodes:
      - "project"
      - "sequence"
      - "video"
      - "audio"
    supported_features:
      - "multi_track"
    unsupported_nodes:
      - "metadata"
      - "effects"
      - "subtitle_track"
    compatible_with: ["1.0"]
  
  "1.0":
    description: "初始版本"
    schema: "jianying_v1.xsd"
    required_nodes:
      - "project"
      - "sequence"
      - "video"
      - "audio"
    supported_features:
      - "single_track"
    unsupported_nodes:
      - "metadata"
      - "effects"
      - "subtitle_track"
      - "multi_track"
    compatible_with: []

# 版本迁移路径（用于自动找到最佳迁移路径）
migration_paths:
  "3.0-1.0": ["3.0", "2.0", "1.0"]
  "2.5-1.0": ["2.5", "2.0", "1.0"]

# 默认版本设置
default_settings:
  compatibility:
    target_version: "3.0"
    check_updates: true
    update_interval: 7
    auto_adapt: true
    fallback_enabled: true
  
  schemas:
    default_schema: "jianying_v3.xsd"
    validation_level: "normal"
  
  features:
    required_nodes:
      - "project"
      - "sequence"
      - "video"
      - "audio"
    supported_features:
      - "multi_track"
      - "effects_layer"
      - "subtitle_track" 