# 时空折叠引擎配置文件

# 全局设置
default:
  structure: "倒叙风暴"
  strategy: "倒叙风暴"
  folding_mode: "preserve_anchors"  # preserve_anchors, condense_similar, highlight_contrast, narrative_driven
  preserve_anchor_threshold: 0.7    # 保留锚点的重要性阈值
  scene_similarity_threshold: 0.75  # 场景相似度阈值
  min_scene_duration: 2.0           # 最小场景时长(秒)
  allow_adaptive_folding: true      # 允许自适应折叠

# 折叠策略配置
strategies:
  # 倒叙风暴策略
  flashback_storm:
    name: "倒叙风暴"
    description: "从高潮点开始，通过回忆和闪回构建叙事"
    structure_types: ["倒叙风暴", "flashback_storm"]
    fold_ratio: 0.5
    preserve_start: false
    preserve_end: true
    anchor_weights:
      climax: 2.0
      emotion: 1.5
      suspense: 1.4
      revelation: 1.3
      character: 1.0
      transition: 0.8
      resolution: 0.9
    highlight_features:
      climax_first: true
      emotion_contrast: true
  
  # 多线织网策略
  multi_thread:
    name: "多线织网"
    description: "交织多条故事线，强调人物关系和情感变化"
    structure_types: ["多线织网", "multi_thread"]
    fold_ratio: 0.3
    preserve_start: true
    preserve_end: true
    anchor_weights:
      character: 1.8
      transition: 1.5
      emotion: 1.2
      climax: 1.0
      suspense: 1.0
      revelation: 1.0
      resolution: 0.9
    highlight_features:
      character_focus: true
      transition_points: true
  
  # 环形结构策略
  circular_narrative:
    name: "环形结构"
    description: "首尾呼应，形成循环叙事结构"
    structure_types: ["环形结构", "circular_narrative"]
    fold_ratio: 0.4
    preserve_start: true
    preserve_end: true
    anchor_weights:
      transition: 1.7
      resolution: 1.6
      emotion: 1.2
      character: 1.1
      suspense: 0.9
      climax: 1.0
      revelation: 1.0
    highlight_features:
      start_end_connection: true
      thematic_elements: true
  
  # 高潮迭起策略
  escalating_peaks:
    name: "高潮迭起"
    description: "多个高潮点递进，不断提升紧张感"
    structure_types: ["高潮迭起", "escalating_peaks"]
    fold_ratio: 0.25
    preserve_start: true
    preserve_end: true
    anchor_weights:
      climax: 1.9
      emotion: 1.6
      suspense: 1.5
      revelation: 1.3
      character: 1.0
      transition: 1.0
      resolution: 1.0
    highlight_features:
      multiple_climaxes: true
      emotional_progression: true
  
  # 并行蒙太奇策略
  parallel_montage:
    name: "并行蒙太奇"
    description: "两条故事线并行发展，通过交替场景展现"
    structure_types: ["并行交替", "parallel_montage"]
    fold_ratio: 0.3
    preserve_start: true
    preserve_end: true
    anchor_weights:
      character: 1.6
      transition: 1.8
      emotion: 1.2
      suspense: 1.0
      climax: 1.1
      revelation: 1.0
      resolution: 1.0
    highlight_features:
      character_alternation: true
      perspective_shifts: true

# 折叠模式配置
folding_modes:
  preserve_anchors:
    description: "保留关键锚点的折叠方法，压缩非关键场景"
    importance_decay: 0.7  # 相邻场景的重要性衰减率
    allow_importance_overlap: true
  
  condense_similar:
    description: "压缩相似场景的折叠方法"
    minimum_similarity: 0.75
    max_consecutive_similar: 3
    condensation_factor: 0.3
  
  highlight_contrast:
    description: "强调情感对比的折叠方法"
    contrast_threshold: 0.5
    emotion_priority: 1.5
    contrast_window_size: 3
  
  narrative_driven:
    description: "基于叙事结构的折叠方法"
    structure_adherence: 0.8
    allow_creative_reordering: true

# 模型配置 - 保留英文模型配置但不加载
models:
  scene_similarity:
    chinese:
      path: "models/scene_similarity/chinese_similarity"
      threshold: 0.7
      enabled: true
    english:
      path: "models/scene_similarity/english_similarity"
      threshold: 0.7
      enabled: false  # 暂不加载英文模型
  
  narrative_coherence:
    chinese:
      path: "models/coherence/chinese_coherence"
      threshold: 0.6
      enabled: true
    english:
      path: "models/coherence/english_coherence"
      threshold: 0.6
      enabled: false  # 暂不加载英文模型

# 可视化配置
visualization:
  color_scheme:
    climax: "#E63946"
    flashback: "#457B9D"
    emotion_high: "#F4A261"
    emotion_low: "#2A9D8F"
    character_focus: "#264653"
  
  timeline_display:
    show_original_position: true
    highlight_fold_points: true
    show_importance_scores: true 