name: Translate Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/zh_CN/**'
      - 'docs/USER_GUIDE.md'
      - 'docs/API_REFERENCE.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/zh_CN/**'
      - 'docs/USER_GUIDE.md'
      - 'docs/API_REFERENCE.md'
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # 安装文档工具所需的依赖
        pip install pyyaml markdown

    - name: Check for document changes
      id: check_changes
      run: |
        python tools/doc_translator.py --check > doc_changes.txt
        cat doc_changes.txt
        if grep -q "需要更新的文档总数: 0" doc_changes.txt; then
          echo "No document changes detected"
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "Document changes detected"
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Sync documents
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        python tools/doc_translator.py
        echo "Documents synchronized locally"
    
    - name: Commit changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        git commit -m "Auto-translate documents" || echo "No changes to commit"
    
    - name: Push changes
      if: steps.check_changes.outputs.changes == 'true' && github.event_name != 'pull_request'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Trigger GitLocalize (if configured)
      if: steps.check_changes.outputs.changes == 'true' && github.event_name != 'pull_request'
      run: |
        if [ -f .gitlocalize.yml ]; then
          echo "GitLocalize configuration detected. Changes pushed to GitHub will trigger GitLocalize."
          echo "See project settings at https://gitlocalize.com/repo/${{ secrets.GITLOCALIZE_REPO_ID }}"
        else
          echo "No GitLocalize configuration found. Translations were done locally only."
        fi 